### ISSUE TITLE
Download dialog shows no connection although Internet is connected

### ISSUE THREAD

**Issue by aakabir** [UstadMobile/UstadMobile#100]
Sometimes downloader doesn't show the network is not connected.
![VSOSchool 1 (1)](https://user-images.githubusercontent.com/33418194/76385490-fcbbee00-638b-11ea-9504-4c7230f42909.jpeg)

**Comment by mikedawson** [comment]
This is reported to happen more frequently on Xiami Android 10 phone and Samsung Android 4.4 phone. @aakabir can you please post the device information screenshots for those.

It was not possible to reproduce this issue on Nokia 3 with Android 9. I turned wifi on and off, logged in and out, enabled and disabled flight mode, and there were no errors with the download dialog.

**Comment by mikedawson** [comment]
This has been resolved.
