### ISSUE TITLE
Download progress shows above size of file

### ISSUE THREAD

**Issue by aakabir** [UstadMobile/UstadMobile#101]
Max file size is 213 MB but while download it, it goes above 213 MB.
![VSOSchool 1 (2)](https://user-images.githubusercontent.com/33418194/76385522-1c531680-638c-11ea-8867-872567f42796.jpeg)

**Comment by mikedawson** [comment]
Report is that downloads are successful however the size report is inaccurate as above. This was not reproduced immediately. It seems possible that the connection in Dhaka might be more likely to interrupt downloads, and this might be leading to inaccurate numbers being reported

**Comment by mikedawson** [comment]
Obsolete / was fixed.
