### ISSUE TITLE
Offline sharing of app installer not working

### ISSUE THREAD

**Issue by aakabir** [UstadMobile/UstadMobile#102]
> _1.3 -1.4 I'm afraid this is not really part of the Ustad app. This is the built-in bluetooth file sharing that is part of Android. It might be if you are using an older version of Android, and/or there is a lot of WiFi or bluetooth activity in the area that this is slow or unreliable. You might need to consider sharing the APK using a memory card or something like that instead in that case._ 

 

While transfer in peer to peer, the receiver has this type of notification. But in sender's end it already transferring. the file is transfer max 34%. As per response, if the app transfer by memory card. do the content of app (which download from cloud) will be inside?? 

and While peer to peer data transfer, it broken then all the content is not shown in senders end.

![VSOSchool 1 (3)](https://user-images.githubusercontent.com/33418194/76385783-d34f9200-638c-11ea-9928-2c37c2558e7a.jpeg)
![VSOSchool 1 (4)](https://user-images.githubusercontent.com/33418194/76385785-d5195580-638c-11ea-99f8-20b708422474.jpeg)

**Comment by mikedawson** [comment]
The sharing of the app installer (e.g. the APK) as per these screenshots is being handled by the underlying Android OS bluetooth system. This is outside of our control. If there is a lot of WiFi and/or Bluetooth activity in the area, that can sometimes be slow or unreliable.

We would suggest an alternative means of sharing the APK in the meantime (e.g. memory card).
