### ISSUE TITLE
Download panel buttons are not showing correctly

### ISSUE THREAD

**Issue by aakabir** [UstadMobile/UstadMobile#103]
![VSOSchool 1 (5)](https://user-images.githubusercontent.com/33418194/76385864-0e51c580-638d-11ea-8905-8f17b843bd92.jpeg)

**Comment by mikedawson** [comment]
This is reproduced and appears to be caused by the material design upgrade. Should be fixed in the next few days.

**Comment by mikedawson** [comment]
This is obsolete
