### ISSUE TITLE
Folder path doesn't work properly

### ISSUE THREAD

**Issue by aakabir** [UstadMobile/UstadMobile#104]
While i go deep in folder from root folder (like: New folder>New folder 1>New Folder 2) if press back button, it takes in root folder (like: New Folder 2<New Folder) but it should be like (New Folder 2<New Folder 1<New Folder)

**Comment by mikedawson** [comment]
This is as per Android's navigation specification, but it seems to confuse everyone! The button at the top left is the up navigation, which is supposed to shortcut back to the last level (e.g. root folder). 

We should probably just change this to being the same as back.

**Comment by mikedawson** [comment]
This is also obsolete. Navigation structure has been updated and now uses Android Jetpack navigation
