### ISSUE TITLE
Door database SQLite and Postgres

### ISSUE THREAD

**Issue by varunasingh** [UstadMobile/UstadMobile#109]
**Describe the bug**
Sqlite and Postgres types do not match the expected types in certain cases. 

The cases so far seen and their correct types :

1. BOOL should be INTEGER NOT NULL ON SQLITE
2. BIGINT should be INTEGER NOT NULL ON SQLITE
3. FLOAT should be REAL NOT NULL on SQLITE
4. DOUBLE should be REAL NOT NULL on SQLITE
5. DOUBLE should be DOUBLE precision on POSTGRES

**To Reproduce**
Run the migration test with generated code and it will not pass because of unmatched type. 

**Expected behavior**
Migration tests should pass

**Screenshots**

**Desktop (please complete the following information):**
 -All

**Smartphone (please complete the following information):**
-All

**Additional context**
N/A

**Comment by mikedawson** [comment]
Implemented with pull request #245
