### ISSUE TITLE
Can we add a refresh button on the feeds?

### ISSUE THREAD

**Issue by varunasingh** [UstadMobile/UstadMobile#20]
Maybe a swipe down to refresh or a button to the left of the plus ( + ) sign or even in the Sub menu

**Comment by mikedawson** [comment]
Implemented pull to refresh on Android and J2ME : HTTP Caching functionality needs checked to ensure that cached copies are correctly revalidated.  For the moment this works on the downloaded view to refresh entries from the device.

**Comment by mikedawson** [comment]
Fully implemented with commit d8b3453ec2db4870b49e0ab8dd0931cfc129f0c3 : internal http caching mechanism will check / use cache-control headers.
