### ISSUE TITLE
App crashes when logging in with a user who has an empty first name

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#242]
**Describe the bug**
When logging in as a user with a blank first name, the app will crash

**To Reproduce**
1. Create a user with a blank first name
2. Create an account for the user
3. Login as the user
4. App will crash

**Expected behavior**
App should login

**Additional context**
This happens because of the app attempting to set the user profile's first initial in the app menu at the top - calling String.first with an empty string will crash.

We should either make the first name and last name mandatory - and validate it, or we should rework how the initial at the top is set.

**Comment by poojaustad** [comment]
First name, Last name, and Gender are made mandatory. Validated. This issue is resolved.
