### ISSUE TITLE
Improve management of class enrolments

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#254]
**Is your feature request related to a problem? Please describe.**
Adding and removing students from a class is not as simple as other relationships. Ending their enrollment does not mean that the enrolment never happened. The user needs a way to see the enrollment info for a given student and to be able to filter a list to show only those that are current active members.

**Describe the solution you'd like**
Add a UI that allows the user to manage the enrollment and filter class members (e.g. show only active members / show all members)

**Comment by poojaustad** [comment]
Class enrollment has been implemented. Validated the same.
