### ISSUE TITLE
Build failing with Ant and Antenna

### ISSUE THREAD

**Issue by baktash93** [UstadMobile/UstadMobile#28]
Hi @mike. I recently wanted to check out UstadMobile (J2ME version) on Windows via a J2ME Emulator and followed the instructions from the `Readme.md` file within the folder `UstadMobile>ports>j2me`. 

But for some reason that I'm not able to understand I end up with errors and cannot build the application.

 Things done before building the application:
---

- I have an installed Java 1.8.0_77 and if I execute the command `java -version` on a console, I get the following: 

          java version "1.8.0_77"
          Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
          Java HotSpot(TM) Client VM (build 25.77-b03, mixed mode)
- Cloned UstadMobile from the repository at [github](`https://github.com/UstadMobile/UstadMobile`)
- Downloaded and installed Wireless Toolkit (WTK) 2.5.2_1 from [Java's website](http://www.oracle.com/technetwork/java/download-135801.html). In addition, added the directory to my pc's PATH under `WTK_HOME`.
- Downloaded and unpacked *apache-ant-1.9.5*. Additionally, added `ANT_HOME` to the PATH.
- Downloaded stable JAR file for `antenna-bin-1.0.2.jar` from [Source Forge](https://sourceforge.net/projects/antenna/files/antenna/).
 
Building the J2ME application through ant and antenna:
--

As per the Readme file within the `ports>j2me` folder I did the following:

 - Ran the command
 
 `cp ustadmobilemicro-build.default.properties ustadmobilemicro-build.properties`

 - On the next step, for setting the path to WTK its indicated to execute the command `export WTK_HOME=/path/to/WTK` on the console. But since I have already added the path for WTK to the `System properties > Advanced > Environment variables > System variables`, `echo`ing out `$WTK_HOME` shows me the added path.

 - In order to build the app I executed the following command (as per the instructions): 

   `ant -f antenna-build.xml -lib /x/antenna/antenna-bin-1.0.2.jar`

  Initially I get the following error log from the console:

        Buildfile: x:\Software\UstadMobile\UstadMobile\ports\j2me\antenna-build.xml
            [echo] wtk.home Set to /path/to/WTK2.5.2
        
        clean:
        [delete] Deleting directory x:\Software\UstadMobile\UstadMobile\ports\j2me\src-preprocessed-ANTENNA
        [delete] Deleting directory x:\Software\UstadMobile\UstadMobile\ports\j2me\classes-ANTENNA
        
        preprocess:
        [wtkpreprocess] **************************************************************
        [wtkpreprocess] * Antenna 1.0.1 initialized for project "UstadMobileMicro"   *
        [wtkpreprocess] * Using Sun Wireless Toolkit 2.5 (CLDC-1.1; MIDP-2.0)        *
        [wtkpreprocess] **************************************************************
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\lib\capabilities.xml not found
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\.\capabilities.xml not found
        [wtkpreprocess] Devices: loading capabilities.xml from classpath
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\lib\groups.xml not found
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\.\groups.xml not found
        [wtkpreprocess] Devices: loading groups.xml from classpath
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\lib\devices.xml not found
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\.\devices.xml not found
        [wtkpreprocess] Devices: loading devices.xml from classpath
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\lib\custom-devices.xml not found
        [wtkpreprocess] Devices: x:\Software\UstadMobile\UstadMobile\ports\j2me\.\custom-devices.xml not found
        [wtkpreprocess] Devices: loading custom-devices.xml from classpath
        Warning: unknown device "Antenna"
        Symbols:
        [wtkpreprocess] Preprocessing 105 file(s) at x:\Software\UstadMobile\UstadMobile\ports\j2me\src
        
        build:
            [mkdir] Created dir: x:\Software\UstadMobile\UstadMobile\ports\j2me\classes-ANTENNA
        
        BUILD FAILED
        x:\Software\UstadMobile\UstadMobile\ports\j2me\antenna-build.xml:84: x:\Software\UstadMobile\UstadMobile\ports\j2me\lib does not exist.
        
        Total time: 0 seconds

    As you may notice, it's saying that the `..\ports\j2me\lib` folder does not exist. 

 - To deal with the previous issue I created an empty `lib` folder manually (not sure if appropriate) and re-ran the command. Now I get around a _hundred errors_ indicating things like:
  
   *  `[wtkbuild] x:\Software\UstadMobile\UstadMobile\ports\j2me\src-preprocessed-ANTENNA\com\ustadmobile\port\j2me\app\FileUtils.java:24: error: package com.ustadmobile.core
.util does not exist`
   *  `[wtkbuild] x:\Software\UstadMobile\UstadMobile\ports\j2me\src-   preprocessed-ANTENNA\com\ustadmobile\port\j2me\app\HTTPUtils.java:44: error: cannot find symbol
[wtkbuild] import com.ustadmobile.core.impl.UMLog;
[wtkbuild]                                 ^
[wtkbuild]   symbol:   class UMLog
[wtkbuild]   location: package com.ustadmobile.core.impl`
   * `[wtkbuild] x:\Software\UstadMobile\UstadMobile\ports\j2me\src-preprocessed-ANTENNA\com\ustadmobile\port\j2me\view\UstadViewFormJ2ME.java:40: error: cannot find symbol
[wtkbuild] import com.ustadmobile.core.impl.UstadMobileSystemImpl;
[wtkbuild]                                 ^
[wtkbuild]   symbol:   class UstadMobileSystemImpl
[wtkbuild]   location: package com.ustadmobile.core.impl`

Hope you can help me in solving this problem. Thanks.

NOTE:
--
 _I will provide you with the whole error log but I avoided adding it here so as to keep the problem description concise. So if you know of any online markdown drafting site, please let me know so that I can add it there._

**Comment by mikedawson** [comment]
Hi,

There were a couple steps that were in the antenna-build.xml file but not in the README file : to be exact:

You need to run ant antenna-build.xml getlibs for it to download required JAR files:
```
$ ant -f antenna-build.xml -lib /path/to/antenna getlibs
```

As you might see from the structure of the project there is a core library which contains the main logic layer of the application and is shared between Android and J2ME.  There is a command that copies it into the j2me directory (the same command as is in the Android directory)

```
$ ./updatecore
```

Then the build should succeed.

**Comment by baktash93** [comment]
Thanks @mikedawson, this time the build was successful.
However, shouldn't the above command also start the emulator? Or do I have to follow some other procedure to run UstadMobile on an emulator?

**Comment by mikedawson** [comment]
Hi,

The build is not set to run the emulator itself.. maybe an idea for the future.  For now you need to use the generated jad/jar file with the emulator that comes along with the WTK.  Alternatively you can use NetBeans (which is what I use) to run / develop on it.  If you use NetBeans you'll need to add the required jars to Netbeans so it knows about them.

-Mike
