### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by SBHII** [UstadMobile/UstadMobile#282]
**Describe the bug**
Cannot build a project on Android Studio

**To Reproduce**
Donwload source code
Try to build the project

![image](https://user-images.githubusercontent.com/38576752/122685774-e35c4f80-d226-11eb-827a-ce9fa73ee6f6.png)

**Comment by mikedawson** [comment]
This issue was caused by the jcenter shutdown and is now obsolete.
