### ISSUE TITLE
Could not download com.ustadmobile.adbscreenrecorder.gradle.plugin-0.1-alpha05.jar on branded version for Tajikistan

### ISSUE THREAD

**Issue by SBHII** [UstadMobile/UstadMobile#284]
Change branch to branded Tajikistan
Sync with Gradle files
![image](https://user-images.githubusercontent.com/38576752/122687420-d3953900-d22f-11eb-9f17-31df90e39ded.png)

**Comment by mikedawson** [comment]
Hi,

The branded versions are normally only updated just before releasing updates. The older branches now get stuck because of the JCenter shutdown (although we do have archive copies of all those builds).

Can you build the primary branch? If so, then I can just make an extra update to the tajikistan branch so that it won't get stuck due to the jcenter issue.

**Comment by SBHII** [comment]
Hi Mike,

@mikedawson 

When i build primary this is where my build fails:

D:\projects\maktab\lib-database-android\build\tmp\kapt3\stubs\debug\com\ustadmobile\core\db\dao\ClazzMemberDao.java:8: error: incompatible types: NonExistentClass cannot be converted to Annotation
@error.NonExistentClass()
      ^D:\projects\maktab\lib-database-android\build\tmp\kapt3\stubs\debug\com\ustadmobile\core\db\dao\ReportFilterDao.java:15: error: element value must be a constant expression
    @androidx.room.Query(value = null)
                                 ^

![image](https://user-images.githubusercontent.com/38576752/122764686-2a932080-d2b9-11eb-82b7-ec55c28e1917.png)

**Comment by SBHII** [comment]
I was able to launch it, not sure how though ))) Can you update the branded branch  as well?

**Comment by mikedawson** [comment]
Merge done. @shoha-hakimjonov can try the branded Tajikistan build?

**Comment by shoha-hakimjonov** [comment]
Hi Mike,

I cannot build on app-branded-maktab-tajikistan ."Could not GET 'https://dl.bintray.com/ustadmobile/adbscreenrecord/com/ustadmobile/adbscreenrecorder/com.ustadmobile.adbscreenrecorder.gradle.plugin/0.1-alpha05/com.ustadmobile.adbscreenrecorder.gradle.plugin-0.1-alpha05.jar'. Received status code 403 from server: Forbidden". 
 Here is the screenshot
![image](https://user-images.githubusercontent.com/38576752/122877970-a3918700-d350-11eb-9d65-35090b68e8c3.png)

**Comment by SBHII** [comment]
Yes @mikedawson Thank you very much!
