### ISSUE TITLE
getConfiguredNetworks need location permission since API 29

### ISSUE THREAD

**Issue by DSOTM-pf** [UstadMobile/UstadMobile#300]
Hi, there, I've found an issue in version 0.3.39, which is downloaded from GooglePlay.

**Describe the bug**
I found the usage of startLocalOnlyHotspot may cause compatibility bugs. 

We used it in two methods: 
- [getLastNetworkIdAdded](https://github.com/UstadMobile/UstadMobile/blob/2dc896f0a169341624d87429640e402cf7971434/sharedse/src/main/java/com/ustadmobile/sharedse/network/NetworkManagerBleHelper.java#L139)
- [deleteTemporaryWifiDirectSsids](https://github.com/UstadMobile/UstadMobile/blob/2dc896f0a169341624d87429640e402cf7971434/sharedse/src/main/java/com/ustadmobile/sharedse/network/NetworkManagerBleHelper.java#L154)

This API needs ACCESS_FINE_LOCATION permission since API 29. The app does not declare, check and request this permission before calling getConfiguredNetworks.

**In API 29**
![image](https://user-images.githubusercontent.com/26241319/129875321-3ed0cd39-fa59-405b-854a-0663c5616bdc.png)

**In API 28**
![image](https://user-images.githubusercontent.com/26241319/129875269-c0049d32-581e-468b-8c22-a991b86686dd.png)

**Expected behavior**
It can be fixed by adding fine location to the manifest, and request for the fine location before calling that API, and also check SDK_INT>28.

**Comment by mikedawson** [comment]
Hi, 

Sorry we missed answering this one for so long. We have to switch to using the companion device manager. Using WifiManager to scan and/or connect directly is no longer something Google wants to allow.

 We have been doing work on peer-to-peer communication on our new library [retriever](https://www.github.com/UstadMobile/retriever). That uses network service discovery. Hopefully over the next weeks we will be able to add the companion device manager support.
