### ISSUE TITLE
Allow users to add subtitles for video

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#343]
The video screen has subtitle support (SRT), but we don't allow users who manually add a video to specify the subtitle file.

The content edit screen should allow subtitle selection when a video file has been selected.

**Comment by mikedawson** [comment]
Expected to complete 16/Sept

**Comment by mikedawson** [comment]
Subtitles displaying on Android and the Web; desktop remaining. Subtitle files uploaded via web need checked.

**Comment by poojaustad** [comment]
Tested the subtitle on Android, and it is working as expected.
