### ISSUE TITLE
Move/Hide buttons are not narrated on the Webapp as expected

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#354]
**Describe the bug**
On Library page the Move/Hide buttons are narrated as buttons only, their actions are not mentioned 

**To Reproduce**
1. Narrator is ON on the laptop
2. Go to 'Library' and select the content
3.  The move/hide buttons appear
4. Move the cursor over the buttons
5. Both MOve/Hide buttons are narrated as buttons only

**Expected behavior**
On the Library page, the Move/Hide buttons are narrated as Move button / Hide button

Uploading 2022-06-29_15h02_00.mp4…

**Comment by mikedawson** [comment]
I'm closing this because this is obsolete - it applies to the old web version.
