### ISSUE TITLE
Primary-Pdf Build 3 || When user import pdf file from android device - the pdf content is not visible to user

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#355]
**Noted on:**
Android App

**Describe the bug**
When a user imports a pdf file from an android device - the pdf content is not visible to the user on android device

**To Reproduce**
1. Go to Library
2. Click on the **+Content** button then click on **Add File** button
3. Select pdf file and click on **save** - Pdf file got added to the library
4. Click on pdf content then click on **OPEN** button
5. Pdf content is not visible - it's blank

**Expected behavior**
When user open a pdf content on app, pdf content should be visible to the user

**Screenshots**

https://user-images.githubusercontent.com/78338755/176854736-2f7830f6-fb92-4ab8-b315-427bd7bad13e.mp4

**Comment by poojaustad** [comment]
**This issue not fixed on latest build**

**Comment by varunasingh** [comment]
Thanks @poojaustad I will look into this

**Comment by varunasingh** [comment]
Hi @poojaustad  this is ready to test in build 8

**Comment by poojaustad** [comment]
Thanks @varunasingh , This issue has been fixed on build 8.
