### ISSUE TITLE
Primary-Pdf Build 3 || When a user imports a pdf file from a web app- the pdf content TITLE  field is not  auto-filled as expected

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#356]
**Noted on :**
Ustad Web app

**Describe the bug**
When a user imports a pdf file from a web app- the pdf content TITLE  field is not  auto-filled as expected

**To Reproduce**
1. Go to Library on the web app
2. Click on the +**content** button and then click on the **Add file** button
3. Select the pdf file and click **upload** button
4. On the Content edit page pdf title is not auto-filled as expected

**Expected behavior**
When a user imports a pdf file from a web app- the pdf content TITLE  field should be  auto-filled

https://user-images.githubusercontent.com/78338755/176855972-3221291c-27f0-4299-bf70-701115fdcbee.mp4

**Comment by varunasingh** [comment]
Hi @poojaustad  this should be ready for testing

**Comment by poojaustad** [comment]
Hi @varunasingh , 

https://github.com/UstadMobile/UstadMobile/issues/363

This issue is blocking this test.

**Comment by poojaustad** [comment]
This issue has been fixed on build 7
