### ISSUE TITLE
Primary -Pdf build 3|| When the user opens a pdf content added through a web app , on the android, the pdf content is visible but it is movable 

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#357]
https://user-images.githubusercontent.com/78338755/176857016-6ed656d7-7edd-47a0-8958-f64f43cdb67b.mp4

**Describe the bug**
When the user opens a pdf content added through a web app , on the android, the pdf content is visible but it is movable 

**To Reproduce**
1. Admin added pdf content to the library through web app
2. User login on android device and click on the pdf content
3. When user click download button then open button
4. The pdf content was visible but when user scrolled within the screen it was moving

**Expected behavior**
When the user opens a pdf content added through a web app , on the android, the pdf content is visible but it should not be movable 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varunasingh** [comment]
Hi @poojaustad this should be ready for testing

**Comment by poojaustad** [comment]
Hi @varunasingh ,

Thanks. https://github.com/UstadMobile/UstadMobile/issues/363 -  issue is blocking this test

**Comment by poojaustad** [comment]
This issue fixed - tested build 7
