### ISSUE TITLE
Omuzgor Mobile || Does not accept links either Youtube or Google Drive.

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#360]
**Observation**

Google Drive links are mentioned in the text on the ContentEntry link page but it is not supporting Google Drive links 
1. Google drive

![2022-07-06_11h20_26](https://user-images.githubusercontent.com/78338755/177701142-de907305-d89e-4a88-b95c-f94314a72290.png)

**Expectation**
Content can be added to the library through links and it has been mentioned users can add google drive files or folders and plain HTTP links. If it's not supporting Google drive links then the text should be removed

**Steps to reproduce**
1. Go to the library 
2. Click on the +Content button and click on Add file through a link
3. Enter a google drive file link - getting an invalid link error

**Comment by mikedawson** [comment]
The text should be changed. Google drive support isn't feasible at the moment. Users can upload normal files from their phone/PC etc using the web and app version.

**Comment by poojaustad** [comment]
This issue is tracked in Taiga - [https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/43](url)

**Comment by mikedawson** [comment]
Text has been updated. Youtube cannot be legally supported because its policies prohibit downloading / extracting videos from the site.Google drive isn't feasible at the moment and the priority is to update the web and implement desktop versions to make it easier for users to upload from their PC.
