### ISSUE TITLE
Omuzgor Mobile || On web app -Image and save icons are not working on text block 

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#361]
**Describe the bug**
On the web app -Image and save icons are not working on text block 

**To Reproduce**
1. Go to Text block
2. Click on the image button and add an image/video- it won't work
3. Click on the save icon - but it won't get saved

**Expected behavior**
The image button should add an image to the text block and the save button should save the text

**Screenshots**
![2022-07-06_11h30_42](https://user-images.githubusercontent.com/78338755/177712563-a881f1f1-02f1-4ba2-bde0-63a50980ba92.png)

**Comment by poojaustad** [comment]
This issue is tracked in Taiga - [https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/44](url)

**Comment by mikedawson** [comment]
Images are not supported here and these buttons have been removed.
