### ISSUE TITLE
Primary-PDF build 6 || Pdf content not able to upload on ustadmobile app through web app

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#363]
**Describe the bug**
An issue is noted when the user tries to upload a pdf file to the ustad app through the web app getting a 500 internal server error.

**Screenshots**
![2022-07-12_10h18_40](https://user-images.githubusercontent.com/78338755/178427233-4b4831aa-a43d-4b80-9e30-28414847550f.png)

![2022-07-12_10h18_18](https://user-images.githubusercontent.com/78338755/178427244-b1dd0f62-99bc-4974-9536-17bbb2dd16ae.png)

**To Reproduce**
1. Go to Library
2. Click on the +Content button
3. Select the pdf file and click on the Upload button
4. The page keeps on loading and getting error 500 on console and server

**Expected behavior**
When the user uploads a pdf file to the app through web app, it should get uploaded without any error

**Comment by varunasingh** [comment]
Thanks @poojaustad  I'll look into it.

**Comment by poojaustad** [comment]
Thanks @varunasingh

**Comment by varunasingh** [comment]
Hi @poojaustad  this is ready for test in build number 7

**Comment by poojaustad** [comment]
This issue fixed. Tested build 7 . Thanks @varunasingh
