### ISSUE TITLE
Omuzgor Mobile || Language: menu, not everything is translated

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#364]
**Describe the bug**
Language: menu, not everything is translated

**To Reproduce**
1. Go to the Ustad web app
2. Click on the Language dropdown and select language
3. Some menu buttons are not translated

**Expected behavior**
When the user change language all buttons should get translated

**Screenshots**
![2022-07-12_12h02_05](https://user-images.githubusercontent.com/78338755/178440912-fd731caa-6e07-420d-9340-513d2d1da06e.png)

**Comment by poojaustad** [comment]
This bug is tracked in Taiga -[https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/46](url)

**Comment by mikedawson** [comment]
Closing this as obsolete as it related to the old web version.
