### ISSUE TITLE
Omzugor Mobile || Font size for assignments is now bigger compared to the font used in other blocks.

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#365]
**Describe the bug**
Font size for assignments is now bigger compared to the font used in other blocks.

**To Reproduce**
1. Go to  Course blocks
2. The title of the Assignment block is a bit bigger compared to the title of other  course blocks

**Expected behavior**
The title of all the course blocks should be the same

**Scre
![2022-07-12_12h19_58](https://user-images.githubusercontent.com/78338755/178447261-daa7cefd-eaea-448e-b72a-215d6b68b9fb.png)
enshots**

**Comment by poojaustad** [comment]
Tracked in Taiga -[https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/47](url)

**Comment by mikedawson** [comment]
This has  been resolved in the MVVM branch.
