### ISSUE TITLE
Update create new user to allow for creation of username/password on the same screen

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#369]
Creating a new user requires two steps: 1) adding the person to the system and 2) creating an account with a username/password. This is done in two different screens (e.g. add person, then create account).

It would be easier for the admin if they could specify the username and password at the same time.

**Comment by varunasingh** [comment]
@poojaustad  this is ready to test on branch primary-authpersonedit on jenkins build 2

**Comment by poojaustad** [comment]
Tested. This enhancement is added to the app
