### ISSUE TITLE
Drag/drop of blocks on Web/Desktop should work without handle

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#373]
Drag/drop of items on web/desktop on other sites doesn't require using a specific handle. We should change course blocks to do the same.

**Comment by poojaustad** [comment]
This enhancement is tracked in Taiga- [https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/33](url)

**Comment by mikedawson** [comment]
Has been implemented in the MVVM version
