### ISSUE TITLE
Primary-PDF build 7 || When the user upload a pdf file using link - user not able to open the content

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#376]
**Describe the bug**
When the user uploads a pdf file using a link - the user is not able to open the content.

Observations - 
On Web app - when user clicks open button - getting pop up saying null

https://user-images.githubusercontent.com/78338755/179709290-b523ad23-5076-4cd0-8a16-936e938da0a8.mp4

On Android - the DOWNLOAD/OPEN button is not visible

https://user-images.githubusercontent.com/78338755/179709363-972b1274-a222-4c38-a3a6-d156808f3395.mp4

**To Reproduce**
1. Go to the content page 
2. Click on the +Content button
3. Click on  - Add using the link button
4. Enter URL
5. Click on the SAVE button
6. Then click on content and click on the Open button -No file found and null pop up appears on Web app
7. Try same steps on android, then user not able to view OPEN button

**Expected behavior**

When the user uploads a pdf file using a link - the user should be able to open the content.

**Comment by varunasingh** [comment]
Hi @poojaustad this is ready to test in build 9

**Comment by poojaustad** [comment]
HI @varuna,

This issue is reproduced on build 8.

Link used - [https://github.com/UstadMobile/UstadMobile/raw/primary-pdf/core/src/jvmTest/resources/com/ustadmobile/core/container/validPDFMetadata.pdf]

Can you please provide another pdf link for the test?

-Thanks

**Comment by varunasingh** [comment]
@poojaustad try build 9

**Comment by poojaustad** [comment]
Thanks, @varunasingh . This issue has been fixed. Tested on build 9
