### ISSUE TITLE
Separation of the role of content creator and teacher/course leader. [enhancement]

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#380]
Currently teacher and content creator are the same role, but in practice some teachers should not have editing rights.

**Comment by poojaustad** [comment]
https://tree.taiga.io/project/mikedawson-ustad-mobile/us/2

**Comment by mikedawson** [comment]
Currently teachers can edit their course. Who can edit a course can be changed in the permissions. When asked the originally proponents said that this was to enable content creators to see how their content would look. They could do that already by changing account to a student account if required.

In reality - the course looks the same for all users, but those with more rights will see other options (e.g. edit). I have not seen any comparable role or feature in any other LMS.
