### ISSUE TITLE
Not possible to delete users by admin. 

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#382]
When bulk user registration is enabled it will be good to make possible to delete some users by admin.

**Comment by poojaustad** [comment]
https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/50

**Comment by poojaustad** [comment]
[Screencast from 2024-12-05 16-54-08.webm](https://github.com/user-attachments/assets/3f7b696b-5968-4b5f-9e91-a227a81a0570)

To delete an existing student from a course, On the course member list

1. Click on the user name
2. Click on edit enrolment icon
3. Select the enrolment end date and outcome reason
 
 This will delete the user from course member list.
