### ISSUE TITLE
Not possible to delete courses.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#384]
Make possible to delete course by admin (or course owner).

**Comment by poojaustad** [comment]
https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/35

**Comment by mikedawson** [comment]
Courses cannot be deleted, but the course end date can be set. Inactive courses are not shown by default. Just because a course is over doesn't normally mean the data (grades etc) should be deleted.
