### ISSUE TITLE
Difficulty with changing interface language in mobile version after login.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#386]
User can choose platform interface language only when welcome screen (before login), but after entering platform user cannot find option to switch the language. Recommendation to put switch language option in user profile or settings section.

**Comment by poojaustad** [comment]
Tracking on Taiga - https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/63

**Comment by mikedawson** [comment]
This was added to settings.
