### ISSUE TITLE
It's hard to find the option to upload a new file for a course, it's difficult.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#388]
This is possible, but it is quite difficult to navigate this option, when user needs to edit the course navigate and open new course blocks, then choose file from blocks, then library opens and it is confusing (needs to open "My content") then user needs to navigate upload my own file, then click to the area or "cloud", the select file from his computer/device, then press upload button...

Improve navigation for new file uploading. Implement status or file upload progress indication.

**Comment by poojaustad** [comment]
https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/37

**Comment by mikedawson** [comment]
No change planned at the moment before launch of the new (MVVM) version. Can consider this UX thereafter if needed.
