### ISSUE TITLE
New file uploading status/progress.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#389]
When user uploads new file for the course and waiting when it will be uploaded, no information regarding progress or status of the uploading (for example for currently unsupported pdf format pdf it behaves like normal upload, but it is not uploading and it's not clear).

**Comment by poojaustad** [comment]
https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/38

**Comment by poojaustad** [comment]
[Screencast from 2024-12-05 16-38-18.webm](https://github.com/user-attachments/assets/4cdeedc7-aaaf-4f0a-88af-b547630ab2a5)

This video shows the importing and uploading progress of a video content file on the Android app

**Comment by poojaustad** [comment]
![Screenshot from 2024-12-05 16-43-13](https://github.com/user-attachments/assets/cc7e244d-81ea-4012-8d0c-8bb0cbe3df4a)

This image shows when user try to upload an unsupported file the app shows error.

**Comment by mikedawson** [comment]
This was completed (a while back) as per the recordings above.
