### ISSUE TITLE
Newly uploaded file description form is not clear for the user.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#393]
When user uploads new file for the course - platform shows form with the file description fields and it is not clear for the user.

Maybe this screen might be improved as well as translation to make it more understandable.

**Comment by poojaustad** [comment]
Tracking on taiga - **https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/40**

**Comment by mikedawson** [comment]
So far... haven't seen too many reports on this being a challenge. Might be considered later if users find file upload non-intuitive.
