### ISSUE TITLE
Course structure blocks icons - title text/prompt.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#394]
[Maybe duplicated] Course structure blocks icons needs title text/prompt for better understanding.

Course structure blocks icons needs titles text/prompt for better understanding.

**Comment by poojaustad** [comment]
Tracked on taiga - https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/41

**Comment by mikedawson** [comment]
Title and text is included, I think this issue is obsolete.
