### ISSUE TITLE
When new file uploaded to the course and user fills file description, where choosing language option - unsaved changes lost.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#396]
When new file uploaded to the course and user fills file description, where choosing language option - unsaved changes lost. Recommended to save form fields, after choosing the language.

**Comment by mikedawson** [comment]
@komil-pro this needs sufficient information to reproduce. This has now been added to Taiga:
https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/10

Can you please add step by step instructions to reproduce the bug and/or a video there?
