### ISSUE TITLE
Two roles: content creator (teacher) and teacher (course leader).

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#404]
(RCITC 2.2) Senior teacher/content creator (accepts the course and requests for the course and organizes them in groups), teacher/course leader (enters the materials on the page of the courses that are allowed to be held and monitors its progress.)

**Comment by mikedawson** [comment]
This is part of the user story to allow custom roles for courses. Tracked here: https://tree.taiga.io/project/mikedawson-ustad-mobile/us/2
