### ISSUE TITLE
Course information/description.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#405]
(RCITC 2.3) Course information (subject, number of hours, start and end, whether diploma or certificate of completion is awarded).

**Comment by mikedawson** [comment]
Start and end is already in the course. Number of hours and whether or not a diploma / certificate is awarded can be added.

**Comment by mikedawson** [comment]
Now tracked on Taiga: https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/1
