### ISSUE TITLE
Displaying only selected course materials (in the library).

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#407]
(RCITC 3.4) For the user, only those materials related to the chosen course should be displayed.

**Comment by mikedawson** [comment]
@komil-pro I do not understand this. When a user is in a course, the content of that course will be displayed. Can you please clarify?

**Comment by komil-pro** [comment]
> @komil-pro I do not understand this. When a user is in a course, the content of that course will be displayed. Can you please clarify?

Actually, this enhancement recommendation came from RCITC workshop and was originally in the Tajik language (the priority of this recommendation is not high, but I can contact and clarify what was meant). [I think it was related to "show only related to subscribed courses materials in lib"]

**Comment by mikedawson** [comment]
@komil-pro if this can be clarified, then we can assess it, otherwise, this issue should be closed.

**Comment by poojaustad** [comment]
Tracking on Taiga - https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/52
