### ISSUE TITLE
Primary-Authpersonedit || Build 3 || Username is case sensitive and users able to create same usernames with different cases 

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#409]
**Describe the bug**
 Username is case sensitive and users able to create the same usernames with different cases 

**To Reproduce**
1. On the people page
2. Click on the +Person button
3. Users with the same name create a username as - **sc** and another user as **SC**
4. Both usernames are accepted - not showing error to users

**Expected behavior**
 The username should be unique and not case-sensitive. Users should not be able to create the same usernames with different cases 

**Screenshots**
![2022-08-04_15h32_18](https://user-images.githubusercontent.com/78338755/182838214-b45408a2-957d-4165-841c-de107dbbd5ef.png)

**Comment by varunasingh** [comment]
Hi @poojaustad this should be ready to test in build 4

**Comment by poojaustad** [comment]
Hi @varunasingh  , Tested build 4.

When a user creates a user name "studenta" another user is not able to create another user name 'STUDENTA'. But when it comes to logging in, if the user name is not case sensitive, then the user should be able to log in if the same user uses username as-STUDENTA or studenta. But getting an error when the user uses username with another case

**Comment by poojaustad** [comment]
https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/12

**Comment by poojaustad** [comment]
obsolete
