### ISSUE TITLE
Mvvm primary- build 60 || Andoid || Issue related to Description field on course page

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#552]
**Describe the bug**
When the user clicks on the 'Description' field it opens a new page. 
When the user adds a text block with a description, the course description gets changed to a text block description.

**To Reproduce**
Issue noted on android app
1. Go to the Courses page and click on the +Course button
2. Enter the course title then Click on the description field- new page appears- add text to it and click on the Done button
3. Scroll down to the '+Add a block' button
4. click on the Text button
5. Enter the text title, click on the description field- add text inside the text block, and click on the Done button
6. click on the Save button to save changes
7. The course description changed same as the text block  description

**Expected behavior**
The description is an optional -text field. It should not open a new page and the course description should not change with a change in text/assignment block description 

**Screenshots**
[device-2023-07-13-143729.webm](https://github.com/UstadMobile/UstadMobile/assets/78338755/81811c37-2471-4f31-8c5a-48492f73249d)

**Comment by mikedawson** [comment]
Hi @poojaustad I think this was fixed a while back. Can you please re-check, and close if fixed? Thanks.

**Comment by poojaustad** [comment]
This issue is fixed
