### ISSUE TITLE
Usability || Clear Differentiation Between Mandatory and Optional Fields

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#560]
**Is your feature request related to a problem? Please describe.**

The current design of the application's forms lacks a clear and intuitive way for users to differentiate between mandatory and optional fields during data entry. To address this, this enhancement proposes the implementation of a visual distinction by marking mandatory fields with an asterisk (*) and optional fields with the label "(optional)".

**Describe the solution you'd like**

Introduce a visual distinction between mandatory and optional fields by using the following conventions:

1. Mandatory Fields: Mark mandatory fields with a red asterisk (*) next to the field label. This simple visual cue will quickly alert users to the fact that these fields are required for successful form submission.
2. Optional Fields: Add the label "(optional)" in gray or another subtle color after the field label for optional fields. This provides clarity and reassurance to users that they can skip these fields if they wish.

**Additional context**

1. Accessibility: Ensure that the new visual cues are accessible to users with visual impairments, by using appropriate HTML tags and providing alternative text.
2. Localization: Consider that the labeling conventions may need to adapt for languages with different sentence structures.

**Comment by mikedawson** [comment]
Can be implemented as per https://m3.material.io/components/text-fields/guidelines#6c36a812-273d-4f5d-9102-2f00386c9145

**Comment by mikedawson** [comment]
TODO: Check all edit screens ( ClazzEdit, CourseBlockEdit, PersonEdit, ContentEntryEdit) to ensure that the name / title is marked as required and validated (must not be null or empty)

**Comment by poojaustad** [comment]
Validated and working as expected
