### ISSUE TITLE
Usability || Contextual Help for Form Fields

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#562]
**Is your feature request related to a problem? Please describe.**

This enhancement aims to improve user understanding and data accuracy by implementing contextual help text for such fields, ensuring users have clear guidance without compromising the usability of the form.
Fields with specific input requirements or application-specific constraints can lead to confusion if users are not aware of the expected format.

**Comment by mikedawson** [comment]
There are no fields with application specific constraints (except username/password). Adding contextual help here would not be needed and will add to translation issues.
