### ISSUE TITLE
Usability || Inconsistent Field Sizing and Unnecessary Full-Width Form Fields

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#563]
**Describe the bug**

The current layout of form fields within the application lacks consistent sizing based on the expected content. Some fields appear to have unnecessary screen-wide widths, leading to suboptimal user experience and readability. T

**To Reproduce**
1. Go to People page
2. Click on +Person button
3. See form fields 

**Expected behavior**

- Form fields should be appropriately sized based on the expected content and user input. Fields like year values should have enough width for their content (e.g., four digits), while other fields like description should have a width conducive to readability and user understanding.

**Screenshots**
![Screenshot from 2023-08-15 16-11-14](https://github.com/UstadMobile/UstadMobile/assets/78338755/aca6f08d-5171-4048-9046-5997a1906633)
![Screenshot from 2023-08-15 16-07-18](https://github.com/UstadMobile/UstadMobile/assets/78338755/3325639e-b3b8-466d-afeb-053cf8c8d86a)

**Additional context**

- Implement dynamic field sizing based on the expected content. For instance, year values should accommodate four digits, while description fields should have a maximum width conducive to readability (e.g., around 80 characters).
- On mobile interfaces, consider using full-width fields to improve user interaction and selection.

**Comment by mikedawson** [comment]
I have not seen dynamic sizing in fields (see attached screenshot from Google contacts etc) in common use. I think this would look pretty strange. All fields are the same width.

![Screenshot from 2023-08-18 16-33-06](https://github.com/UstadMobile/UstadMobile/assets/4280622/611dfe6f-70de-44db-81ab-c8b5df853c4e)

On the web we are using the standard container that adds spacing on the left/right on larger screens. 

It is noted that the birthday field on mobile should take the full width. We do not intend to implement dynamic sizing as this is not common practice and not used in material design.
