### ISSUE TITLE
Usability || Enhanced Navigation, Contextual Information, and User Profile Features

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#565]
**Is your feature request related to a problem? Please describe.**

To improve the overall navigation experience, provide a better context within the application's hierarchy, and enhance user profile management features. By implementing these suggestions, we can enhance user understanding of their current location within the application, display important information in a user-friendly manner, and ensure better security and user management.

**Describe the solution you'd like**

1. Highlight Active Navigation Option:

-  Implement a visual highlighting effect for the active navigation option in the sidebar. This helps users quickly understand where they are within the application's hierarchy.

2. Display Title in Right Panel:

-  Move the title, which is currently displayed at the top navigation bar, to the right-side panel. This is particularly beneficial for sidebar-based layouts and helps users identify the context of the page.

3. Logout Link:

- Add a logout link to the user interface. Currently, there is no way for users to log out, which could potentially pose a security risk for users on shared devices.

4. Profile Page:

- Introduce a profile page where users can access and manage their profile information. This provides users with a clear understanding of the account they are logged into.

**Additional context**

1. Navigation Sidebar:

- Implement CSS or UI changes to visually highlight the active navigation option.

2. Logout Link:

- Add a "Logout" link/button, ideally in the user profile dropdown menu 

3. Profile Page:

- Design and create a profile page that displays user information and allows users to update their profile settings.

screenshots:
![Screenshot from 2023-08-16 14-12-43](https://github.com/UstadMobile/UstadMobile/assets/78338755/5b5c82a6-d9ec-449d-ae9d-e9f76d7631bf)

**Comment by mikedawson** [comment]
1. Current item will be highlighted on navigation
2. Title on right panel: this won't be added until Kotlin/MUI wrapper is updated to material design 3. In material design 2, the title is in the top bar.
3. Logout link - the profile link will be added to the top right. The user will then be able to logout from there as normal.
4. Can be done via link as above.

**Comment by mikedawson** [comment]
Logout link and profile link is implemented and available.

**Comment by mikedawson** [comment]
1. Current item is now highlighted
![Screenshot from 2023-12-05 16-46-08](https://github.com/UstadMobile/UstadMobile/assets/4280622/1d0e7721-09a4-468d-bd6d-0ccb8a204eff)
2.This was already correct as per the version of Material design being used
3. Logout and profile edit has been added
![Screenshot from 2023-12-05 16-46-24](https://github.com/UstadMobile/UstadMobile/assets/4280622/6793a9b0-0c13-4917-9906-5b7fa9b7b9c3)
4. Profile page accessible as per screenshot above
