### ISSUE TITLE
Usability || Enhanced User Guidance for Adding New Persons

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#567]
**Is your feature request related to a problem? Please describe.**

 To improve user guidance during the process of adding a new person to the application. By enhancing the onboarding experience and providing clear guidance on the next steps, we aim to improve user understanding and efficiency.
The current process of adding a new person lacks clear guidance on the next steps users should take after successfully adding the person. This can lead to confusion and missed opportunities to complete related tasks.

**Describe the solution you'd like**

**Enhanced Onboarding Guidance:**

After successfully adding a new person, display a success page that includes concise guidance on the typical actions that can be taken next.

**Highlight the Next Steps:**

On the success page, emphasize the immediate next steps, such as adding the newly added person to an existing course.

**Comment by mikedawson** [comment]
There is no difference between what you can do immediately after adding a person and what you can when you return to that person. I don't think we should need text here.

The behavior in the app when adding a person is the same as the Android address book. There is no "success screen" on the Android address book saying "now you can make a call, text, etc". 

When it comes to enrolling someone on an existing course, the majority of users in tests went to courses to find the course, then went to members. One or two did try this via persons, so it is possible that someone might try this path.

There are quick action buttons at the top for calling the person, sending a text message, etc. We could add a button there for enrol in course that would appear if the active user had permission to do the enrolment.

We have done tests on this flow with teachers (primarily in Lebanon). This showed that the current flow does work. I don't see evidence that adding more text guidance is required. I think this would just clutter up the UI. When the UI is intuitive (as it actually has been proven to be for this use case), there is no need for additional text guidance.
