### ISSUE TITLE
Usability || Enhanced Workflow for Anonymous (Unlogged-in) Users

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#568]
**Is your feature request related to a problem? Please describe.**

To improve the workflow for anonymous (unlogged-in) users by providing a more streamlined and user-centric experience. The goal is to evaluate the accessible screens for guest users and ensure that only relevant and accessible content is displayed, eliminating confusion and enhancing the user journey.

**Describe the solution you'd like**

*Evaluate Accessible Screens:*

- Identify the screens and pages that anonymous users have access to.
- Determine whether any of these screens require user authentication for specific functionality.

*User-Centric Content Display:*

Restrict the display of user-specific content (e.g., people, library) on screens that anonymous users cannot access.

*Clear Authentication Prompts:*

For screens requiring authentication, clearly prompt the user to log in or create an account to access specific content or functionality.

**Comment by mikedawson** [comment]
Handling anonymous users will be implemented when the new databasse/sync engine is integrated.

The top level navigation options shown will not be changed; the interface should remain consistent. Empty states will be displayed, and the guidance on those empty states will reference the need to login/create an account where relevant.

**Comment by mikedawson** [comment]
This is now implemented as per https://github.com/UstadMobile/UstadMobile/issues/691
