### ISSUE TITLE
Usability ||  Inconsistent Vertical Alignment of Titles on Courses Page Grid

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#570]
**Describe the bug**

A bug has been identified on the courses page where the vertical alignment of titles within the grid is inconsistent. The issue specifically concerns the alignment of titles and labels adjacent to course names, which should be aligned to the top for consistent visual presentation.

**To Reproduce**

1. Log in to the application.
2. Navigate to the "Courses" page.
3. Observe the vertical alignment of titles and labels displayed next to each course name.

**Expected behavior**

Titles and labels should be consistently aligned to the top next to each course name. This alignment creates a clean and organized appearance within the courses page grid.

**Screenshots**

![Screenshot from 2023-08-17 14-17-56](https://github.com/UstadMobile/UstadMobile/assets/78338755/58f3f85f-2193-47a5-a0b2-e6943699cf51)

**Comment by mikedawson** [comment]
This is now fixed 

![Screenshot from 2023-12-06 01-29-32](https://github.com/UstadMobile/UstadMobile/assets/4280622/9021a165-18d4-447d-8f44-75ffd23418aa)
