### ISSUE TITLE
Usability || Various Issues on Course Creation Screen - Content Blocks Section

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#571]
**Describe the bug**

This bug report outlines several issues identified within the "Content Blocks" section of the course creation screen. These issues include capitalization inconsistency, unclear functionality, malfunctioning toggles, error message upon adding schedules, and the unexpected disappearance of created course blocks within the same session.

Actual Behavior:

1. Assignment: Completion criteria: The dropdown option "submitted" is displayed where 's' is a small case
2. Clicking on "Submission Type" leads to an unclear "Add Groups" screen.
3. Toggles do not switch on/off upon being clicked-(e.g. require file submission and require text submission etc.)
4. "Add Schedule" displays an error message.
5. Course blocks disappear within the same session. (Not able to reproduce this bug) 

**To Reproduce**

1. Log in to the application.
2. Navigate to the course creation screen.
3. Begin creating course blocks within the same session.

**Expected behavior**

1. Assignment: Completion criteria: Dropdown option "submitted" to be capitalized 
2. Clicking on "Submission Type" should provide clear information about its function.
3. Toggles should switch on/off as expected when clicked.(e.g. require file submission and require text submission etc.)
4. "Add Schedule" should open the schedule interface without any error message.
5. Created course blocks should remain visible within the session.

**Screenshots**
1.
![Screenshot from 2023-08-17 16-57-43](https://github.com/UstadMobile/UstadMobile/assets/78338755/0d49b664-9e69-4723-aad3-7fe6a3106d95)

2.
![Screenshot from 2023-08-17 16-58-57](https://github.com/UstadMobile/UstadMobile/assets/78338755/9936d4a8-42ce-4bf0-8187-5a6f196e348a)

3.
![Screenshot from 2023-08-17 15-07-22](https://github.com/UstadMobile/UstadMobile/assets/78338755/4769a384-edd9-47e1-9c18-2ba3b09a9921)

4.
![Screenshot from 2023-08-17 17-00-11](https://github.com/UstadMobile/UstadMobile/assets/78338755/2fb6f968-6e9f-4b22-a276-3ded79877732)

**Comment by poojalakshmipravi** [comment]
The above bugs are reported as separate issues on Git Hub, closing this issue. Please find the corresponding issue links below:

1. Assignment: Completion criteria: The dropdown option "submitted" is displayed where 's' is a small case

[https://github.com/UstadMobile/UstadMobile/issues/583](https://github.com/UstadMobile/UstadMobile/issues/583)

2. Clicking on "Submission Type" leads to an unclear "Add Groups" screen.

[https://github.com/UstadMobile/UstadMobile/issues/587](https://github.com/UstadMobile/UstadMobile/issues/587)

3. Toggles do not switch on/off upon being clicked-(e.g. require file submission and require text submission etc.)

[https://github.com/UstadMobile/UstadMobile/issues/584](https://github.com/UstadMobile/UstadMobile/issues/584)

4. "Add Schedule" displays an error message.

[https://github.com/UstadMobile/UstadMobile/issues/549](https://github.com/UstadMobile/UstadMobile/issues/549)
