### ISSUE TITLE
Usability || Course Members Tab Improvements

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#572]
**Is your feature request related to a problem? Please describe.**

On the user experience and functionality of the "Course Members" tab, the current user interaction process presents challenges in bulk addition, unclear interface elements, and inadequate feedback during certain actions. Addressing these aspects will result in a more efficient and user-friendly experience.

**Describe the solution you'd like**

*Bulk Addition of Members:*

- Implement a bulk addition feature that enables users to add multiple members (teachers/students) simultaneously, alleviating the need to select each member individually.

*Clarify Outcome Field for Adding a Teacher:*

- Enhance the teacher outcome field by removing irrelevant options and providing clear context about its purpose. This will reduce confusion and ensure users accurately input relevant information.
![Screenshot from 2023-08-18 15-04-08](https://github.com/UstadMobile/UstadMobile/assets/78338755/5ef1bdbc-efa1-4440-a294-7200ec4808d0)

*Improved User Feedback for Failed Student Addition:*

- Enhance the error feedback mechanism when attempting to add a new student (new person). If the attempt fails during saving, display an informative error message that communicates the issue to the user.

**Comment by mikedawson** [comment]
The outcome failed isn't applicable for teachers, but as of right now, I don't think this is directly causing any significant issues for users.

**Comment by mikedawson** [comment]
The screen has been updated to remove the outcome option when the teacher role is selected.

![Screenshot from 2023-12-05 13-30-13](https://github.com/UstadMobile/UstadMobile/assets/4280622/579d69be-c596-436b-b122-bd408cbd26de)

![Screenshot from 2023-12-05 13-30-20](https://github.com/UstadMobile/UstadMobile/assets/4280622/65b28cf0-e439-43aa-b492-1774a653e739)
