### ISSUE TITLE
Usability || Blank Page When Clicking on Existing Group in Course Groups Tab

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#574]
**Describe the bug**

This bug report highlights an issue within the "Course - Groups" tab, where clicking on an existing group leads to a blank page with only an "Edit" button displayed at the bottom. The issue is exacerbated by the lack of proper error handling on the "Add New Group" page, where users are allowed to save without assigning course members to a group.

1. On the "Add a New Group" page, users are allowed to save without assigning course members to the new group, resulting in incomplete and ambiguous groups.
2. Clicking on an existing group with no assigned course members results in a blank page with only an "Edit" button displayed at the bottom.

**To Reproduce**

1. Log in to the application.
2. Access the Course - "Groups" tab.
3. Click on the "+Groups" button 
4. Add the title and click on the "Save" button - a blank page appears
5. Click back button
6. Click on a newly added group that leads to a blank page.

**Expected behavior**

1. Clicking on an existing group should lead to a page that displays relevant information about the group, including its name, members, and other details.
2. On the "Add a New Group" page, an error should be displayed when attempting to save without assigning course members, preventing incomplete groups from being created.

**Screenshots**
[Screencast from 08-18-2023 03:30:52 PM.webm](https://github.com/UstadMobile/UstadMobile/assets/78338755/254b8406-4961-4343-8207-6c24d95abc03)

**Comment by mikedawson** [comment]
This has been fixed as per the video below:

[Screencast from 2023-12-05 17-03-19.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/99adbae2-9349-4f07-89c4-ede54a1704cd)
