### ISSUE TITLE
Usability || Inactive Search Field on "Join Existing Class" Page

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#575]
**Describe the bug**

This bug report addresses an issue on the "Join Existing Class" page, where a search field is present at the top of the page but appears to have no functional purpose. Users may find this confusing and may expect the search field to provide search functionality, which is currently not working as intended.

**To Reproduce**

1. Log in to the application.
2. Access the "Join Existing Class" page.
3. Observe the presence of the search field.
4. Attempt to use the search field to search for classes.

**Expected behavior**
The search field on the "Join Existing Class" page should provide users with the ability to search for existing classes based on search queries, displaying relevant results or should remove that search field.

**Screenshots**
![Screenshot from 2023-08-18 15-56-26](https://github.com/UstadMobile/UstadMobile/assets/78338755/c59ffe45-e078-4847-83ed-ca5a29a9b1ef)

**Comment by mikedawson** [comment]
This has been resolved with the latest builds as per #616
