### ISSUE TITLE
Usability || : Form Obstruction and Ambiguity on Library's New Folder Creation

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#576]
**Describe the bug**

This bug report highlights two issues on the "Library" page: a form obstruction and field ambiguity when creating a new folder. The form presented upon clicking the "+ Content" button is partly obstructed by the header, and certain form fields lack clarity, causing confusion during folder creation.

*Form Obstruction by Header:*
When attempting to create a new folder in the "Library," the form presented is obstructed at the top by the header. This hinders user interaction and visibility within the form.

*Ambiguous Form Fields:*
The form for creating a new folder contains fields that lack clarity in their descriptions. For example, "title" could be better replaced with "folder name," and the purpose of fields such as "author," "publisher," and "license" is unclear when creating a folder.

**To Reproduce**

1. Log in to the application.
2. Navigate to the "Library" page.
3. Click the "+ Content" button to create a new folder.
4. Observe the form obstruction caused by the header and the ambiguity in form field descriptions.

**Expected behavior**

1. The form for creating a new folder should be fully visible and accessible, without any obstruction.
2. Form fields should have clear and self-explanatory labels that accurately represent their intended purpose

**Comment by mikedawson** [comment]
I don't think the form fields are ambiguous. The same fields are applied to both content items themselves (e.g. videos, interactive exercises, ebooks, etc) as well as folders.

Some of the fields are not well understood (e.g. license) by all users, but they are still needed. It has been noted that we need to distinguish between optional and mandatory fields (only the title in this case). 

Even if users don't understand all fields, this isn't a problem as long as they understand that those fields are not mandatory.

**Comment by mikedawson** [comment]
TODO: 
Add * to end of title on ContentEntryEdit to indicate that it is a required field
Add * Required as caption for title field (on Jetpack compose: can use UstadInputFieldLayout captionIfNoError).
Check that validator will block saving if title is empty or null

**Comment by mikedawson** [comment]
This is now implemented. Title field is marked as required (validated when user clicks save). Spacing / cut-off at the top is fixed.

![Screenshot from 2023-12-06 01-01-55](https://github.com/UstadMobile/UstadMobile/assets/4280622/09d2b514-5a20-48e8-a0da-76c3d8a3b09a)
