### ISSUE TITLE
Usability || Labeling and Date Validation Issues on "Add a New Person" Form

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#577]
**Describe the bug**

This bug report addresses two distinct issues on the "People" page, specifically within the "Add a New Person" form. The issues pertain to inaccurate labeling of the email field and the absence of date validation, resulting in potential inaccuracies and confusion during the process of adding a new person.

*Inaccurate Email Field Labeling:*
The "Add a New Person" form requests the entry of a parent's email address. This label implies that the field is specifically for adding students, but it is not appropriately labeled as such.

*Lack of Date Validation for Birthdate:*
The form allows the entry of future dates of birth for individuals. This absence of date validation may lead to inaccuracies and confusion regarding an individual's actual birthdate.

**To Reproduce**

1. Log in to the application.
2. Access the "People" page.
3. Proceed to the "Add a New Person" form.
4. Observe the labeling of the email field and the absence of date validation for birthdate.

**Expected behavior**

1. Inaccurate email field labeling may lead to confusion regarding which individuals the field is intended for.
2. Lack of date validation for birthdate can result in inaccurate records and confusion about individuals' actual birthdates.

**Comment by mikedawson** [comment]
TODO: 
On PersonEditViewModel, validate that the selected date of birth is before current time.

Create new email validation function: this should not use regex. This should be a common function that should check the following (as per https://www.rfc-editor.org/rfc/rfc5322 section 3.4.1 ):

Address must have at least one @ sign
Address must have at least one . after the @ sign
Must not have any spaces, [, ], or \

**Comment by mikedawson** [comment]
Validation is now applied to the date of birth (future dates prohibited). If an email is entered, it must be valid as per the above rules. Email address is not required.

The incorrect display of the parental email address field was removed.

![Screenshot from 2023-12-06 00-49-36](https://github.com/UstadMobile/UstadMobile/assets/4280622/ce821872-405c-4522-ad19-018abf7c7a27)
