### ISSUE TITLE
Usability || Multiple Issues on Course Creation Screen

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#578]
**Is your feature request related to a problem? Please describe.**

1. Missing Vertical Scrolls on Timezone Screen:
- The "Course Edit" screen lacks vertical scroll functionality on the Timezone screen. This oversight prevents users from accessing content below the initial viewport.

2. Absence of Default Range on Start Date Calendar:
- The start date calendar on the "Course Edit" screen should have a default range that excludes past dates. Presently, past dates are available for selection.

3. Lack of Size Limit and Word Count Validation:
- The "New Assignment" screen lacks proper validation for size limits (in MB) and maximum word counts, potentially allowing submissions that exceed acceptable limits.

**Describe the solution you'd like**

1. The Timezone screen should display vertical scrolls to allow users to access content beyond the initial viewport.
2. The start date calendar should have a default range that excludes past dates, ensuring accuracy during date selection.
3. The "New Assignment" screen should perform proper validation for 

- Size limit (MB) in the new assignment screen should have validation (min and max values). 
- Similarly, the maximum number of words should be validated.

**Comment by mikedawson** [comment]
1. The timezone does allow scrolling: whether or not it will explicitly show scroll bars depends on the browser/underlying platform.
2. On the calendar: it is possible that teachers/admins may create their courses retrospectively (e.g. day after etc). We therefor don't intend to block using a past date. We implement a validation to ensure that if the end date is set, it must be after the start date.

**Comment by mikedawson** [comment]
On the maximum number of words: I don't see any need to validate this. Any positive integer is fine. Maybe someone wants a 5 word limit for reflections, or a 100,000 word limit. Both would be valid.

TODO: 

Add validation for for assignment size limit: must be between 5 and 100MB

**Comment by mikedawson** [comment]
![Screenshot from 2023-12-05 16-30-49](https://github.com/UstadMobile/UstadMobile/assets/4280622/a4cee657-27c9-4baf-9f18-085ee983c62b)

Validation on file size is now implemented.
