### ISSUE TITLE
Assignment dropdown criteria not capitalized correctly

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#583]
**Describe the bug**
Assignment: Completion criteria: Dropdown option "submitted" to be capitalized 

**To Reproduce**
Edit a course, add/edit an assignment, then see the completion criteria dropdown.

**Comment by poojalakshmipravi** [comment]
https://user-images.githubusercontent.com/78338755/261315170-0d49b664-9e69-4723-aad3-7fe6a3106d95.png

**Comment by mikedawson** [comment]
TODO: Capitalize the text of the dropdown using .capitalize() as per https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/capitalize.html

**Comment by mikedawson** [comment]
![Screenshot from 2023-11-27 16-37-59](https://github.com/UstadMobile/UstadMobile/assets/4280622/adcfa83d-6bc2-4496-9723-865e288225a7)
Fixed with commit https://github.com/UstadMobile/UstadMobile/commit/3e3d55d0be82d1c2e1ab47871e88a55ea5eb99d3
