### ISSUE TITLE
Toggles not working on Microsoft edge

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#584]
**Describe the bug**
Toggles not working on Microsoft edge

**To Reproduce**
1. Go to edit a course using Microsoft edge
2. Add/edit an assignment
3. Try to change the toggles (e.g. file submission required)

**Expected behavior**
Click toggle should toggle it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: MS Edge

**Comment by mikedawson** [comment]
@poojaustad can you please check this on MS Edge? I think it is now available for Ubuntu.

**Comment by poojaustad** [comment]
This issue is not fixed on the assignment page, tried 

- Allow class comments from students
- Allow private comments from students 
Even these toggles are off , student able to view both comment fields

**Comment by mikedawson** [comment]
This seems to work fine now. Might be that Edge, or MUI, or both updated in the meantime. Tested on the latest dev-mvvm-primary version and Microsoft Edge 119.0.2151.97 (on Ubuntu).

[Screencast from 2023-12-05 16-53-02.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/de81c80c-b59f-4dc1-873e-b0c81e0cbbf8)
