### ISSUE TITLE
Usability || Clicking on "Submission Type" leads to an unclear "Add Groups" screen.

### ISSUE THREAD

**Issue by poojalakshmipravi** [UstadMobile/UstadMobile#587]
**Describe the bug**

Clicking on "Submission Type" leads to an unclear "Add Groups" screen.

**Expected behavior**

Clicking on "Submission Type" should provide clear information about its function. Separate the '+ Add Group' from existing groups to be more clear for the user.

[https://user-images.githubusercontent.com/78338755/261315466-9936d4a8-42ce-4bf0-8187-5a6f196e348a.png](https://user-images.githubusercontent.com/78338755/261315466-9936d4a8-42ce-4bf0-8187-5a6f196e348a.png)

**Comment by mikedawson** [comment]
Improved: added a new switch to set group submission mode on and off. If group submission mode is on, then the user must select the groups. An error message is displayed if group submission is on and no groups are selected.

[Screencast from 2023-12-05 22-08-30.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/7e35ff60-746e-4c5e-ba9b-7bcd07b25dcd)
