### ISSUE TITLE
Mvvm-primary-doorupdate build || Hide/ delete actions are visible in course edit page but when save those files are not hidden/deleted in course overview

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#589]
**Describe the bug**
Hide/ delete actions are visible on the course edit page but when saved those files are not hidden/deleted in the course overview

**To Reproduce**
1. Go to the course page
2. Add Module and Text block
3. Click on the 3 dots button next to the Text block and click on the Hide button
4. Click on the Save button
5. Text block is visible which is not expected

**Expected behavior**
Hide/ delete actions are visible on the course edit page and when saved those files should be hidden/deleted in the course overview

**Screenshots**

https://github.com/UstadMobile/UstadMobile/assets/78338755/c3584fdc-eb28-47e3-a5d0-ae626b4db495

**Comment by mikedawson** [comment]
@poojaustad I fixed this a little while back I believe. I tested (as per the screen record below) and it is working as expected. Please confirm / close the issue if resolved.

[Screencast from 2023-11-07 21-40-47.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/daf0f68c-1ebe-4d0c-89aa-507aec58f555)

**Comment by poojaustad** [comment]
Hi Mike, This issue has been resolved. Closing this issue.
