### ISSUE TITLE
MVVM Primary door update || On create account page Confirm password button is not visible

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#590]
**Describe the bug**
On create account page Confirm password button is not visible

**To Reproduce**
1. Go to Create Accounts page
2. Username and New Password fields are visible
3. Confirm password field not visible

**Expected behavior**
On the Create account page New Password and Confirm password buttons should be visible

**Screenshots**
![Screenshot from 2023-10-04 16-36-41](https://github.com/UstadMobile/UstadMobile/assets/78338755/8f10490f-2eeb-49cc-939b-e3d7e6cdf3b5)

**Comment by mikedawson** [comment]
This is the intended behavior. We don't need a confirm password text box when it is possible for the user to display the password by using the unhide button.
