### ISSUE TITLE
Mvvm-Doorupdate branch || Webapp || When teacher login not able to view other member in the course

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#601]
**Describe the bug**
When the teacher login , not able to view other members of the course

**To Reproduce**
1. Admin add 1 teacher and student to a course
2. When teach login , teacher only see teacher in the course

**Expected behavior**
Teacher should able to see student in the class who is added by the admin to same course

**Screenshots**
![Screenshot from 2023-10-20 17-18-56](https://github.com/UstadMobile/UstadMobile/assets/78338755/cd5b0f77-6e6e-4ebb-be71-617bdae1b6c7)

**Comment by poojaustad** [comment]
This issue was noted only while running cypress tests

**Comment by mikedawson** [comment]
This appears to only be about the total of the students showing on the list of courses. When you go into the members list, the teacher can see the students. These are the wrong totals, but it would have minimal impact on the user

[Screencast from 2023-11-07 21-29-34.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/9f6b214c-a5a9-47fe-8400-e76f9c3ac23d)

The way this works offline-first at the moment, it would have to download a list of all enrolments for all the courses visible, which we want to avoid. This could be handled by creating a summary entity, but for now, it is easier to just remove this info from the course list screen.

Is there anything else?

**Comment by poojaustad** [comment]
Ok MIke, sounds good. Thanks.

**Comment by poojaustad** [comment]
Closing this issue
