### ISSUE TITLE
Cypress Test || When teacher add an assignment in a course,Student not able to view that assignment

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#602]
**Describe the bug**
When teacher add an assignment in a course,Student not able to view that assignment

**To Reproduce**
This issue noted only while running the cypress test, manually it's working as expected

**Expected behavior**
When teacher add an assignment in a course,Student should be able to view that assignment if both are in same course

**Comment by poojaustad** [comment]
Noted- this issue exist when user add assignment hideuntil field

**Comment by mikedawson** [comment]
@poojaustad please check this again. I think this would have been affected by the timezone issue that was seen with assignment deadlines.

**Comment by poojaustad** [comment]
Hi @mikedawson, tested. When adding hide_until_date field still face this issue

**Comment by poojaustad** [comment]
Fixed
