### ISSUE TITLE
Mvvm-Primary-Cypresss Test -Assignment text block and submit button  not visible for student to submit assignment

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#604]
**Describe the bug**
When a student opens an Assignment, text block and the submit button is not visible for the student to submit the assignment. This is noted 3/5 tests while running using cypress

**To Reproduce**
1. Go to cypress test
2. run test -004_001_assignment_creation_submission_grading.cy.js

**Expected behavior**
When a student opens an Assignment, the text block and the submit button should be visible for the student to submit the assignment.

**Screenshots**
![Screenshot from 2023-11-14 12-18-57](https://github.com/UstadMobile/UstadMobile/assets/78338755/aad4c19e-3904-44ae-9be9-3ec80233e0a2)

Expected screen 
![Screenshot from 2023-11-14 12-30-11](https://github.com/UstadMobile/UstadMobile/assets/78338755/8e078fb3-280c-430c-9ea9-2ae1fd88a25d)

**Comment by mikedawson** [comment]
@poojaustad is this only in happening in tests, or can this be reproduced manually?

**Comment by poojaustad** [comment]
Hi @mikedawson , This is not reproduced manually . Only noted in tests.

**Comment by poojaustad** [comment]
cy.wait command resolved this issue. Thanks
