### ISSUE TITLE
1.1 Admin can add files from device or link [Android]

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#606]
1.1 Admin can add H5P, video, EPUB and Experience API zip files from the device and by using a link. Once added the content can be opened. If added on Mobile or Desktop app from the device, testing opening should be from another device or after clearing the app on the device used to upload it.

**Comment by gravitz** [comment]
@mikedawson Expected support for:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/echuwa/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/echuwa/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Content   type | Requirement | Traceability
-- | -- | --
Video | Support for uploading   standard subtitle files, | Inception report
Video | Support for MP4 and   other open, popular file formats | Inception report
Audio | Support for MP3 and   other open, popular file formats | Inception report
H5P | Support for H5P   fullscreen | Sprint 1 backlog
Text/images | Support for text and   images content formats | Inception report
MS-Office | Support for office   documents | Previous discussions   with CO project team



</body>

</html>

**Comment by mikedawson** [comment]
@gravitz adding support for additional content formats (in addition to what was supported in the alpha version) is not part of any current milestone. I have created and tagged a separate issue ( https://github.com/UstadMobile/UstadMobile/issues/765 ) for this.

**Comment by mikedawson** [comment]
Implemented all supported formats as per spec on Android with offline support (including epub):

[epub-video.zip](https://github.com/UstadMobile/UstadMobile/files/14003227/epub-video.zip)
