### ISSUE TITLE
3.2 Admin or teacher can add module and text blocks [Android]

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#627]
3.2 Admin or teacher can add module and text blocks. Blocks can be reordered and hidden, indented, unindented

**Comment by mikedawson** [comment]
@gravitz @atorudsho this is now available.

**Comment by gravitz** [comment]
@mikedawson Available as a release?

**Comment by mikedawson** [comment]
@gravitz The link for downloading APK files is posted on the milestone (files are built and published by our continuous integration server):

https://github.com/UstadMobile/UstadMobile/milestone/8

We won't be publishing them all as releases on Github. There are new versions being put out every day or so.
