### ISSUE TITLE
3.4 Admin or teacher can add a content block and upload new content via link [Android]

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#631]
3.4 Admin or teacher can add a content block and upload new content via link

**Comment by gravitz** [comment]
@mikedawson 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/echuwa/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/echuwa/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">


Content   type | Requirement | Traceability
-- | -- | --
Video | Support for uploading   standard subtitle files, | Inception report
Video | Support for MP4 and   other open, popular file formats | Inception report
Audio | Support for MP3 and   other open, popular file formats | Inception report
H5P | Support for H5P   fullscreen | Sprint 1 backlog
Text/images | Support for text and   images content formats | Inception report
MS-Office | Support for office   documents | Previous discussions   with CO project team



</body>

</html>

**Comment by mikedawson** [comment]
@gravitz adding support for additional content formats (in addition to what was supported in the alpha version) is not part of any current milestone. I have created and tagged a separate issue ( https://github.com/UstadMobile/UstadMobile/issues/765 ) for this.

**Comment by mikedawson** [comment]
Completed in version 0.4.14
