### ISSUE TITLE
 4.1 Teacher can create assignment [Android]

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#641]
4.1 Teacher can create assignment (set to allow one submission per student as per default), student can submit assignment (text and attachment), teacher can view submission and grade it. After submitting their work, the submit button is no longer visible. Student will see their mark when it is graded.

**Comment by gravitz** [comment]
@mikedawson 

Expected that assignment can include completion of quizzes etc. that are created using H5P / Lumi or other external
tools. Traceable back to inception report

**Comment by mikedawson** [comment]
> @mikedawson
> 
> Expected that assignment can include completion of quizzes etc. that are created using H5P / Lumi or other external tools. Traceable back to inception report

@gravitz assignments this was since updated because use of content (H5P etc) within assignments would lead to confusion e.g. course creators could directly add an H5P to a course, but could also add an assignment which would then have an H5P within it. 

Assignments are (as per other Learning Management Systems) therefor only going to be for submitting work that is to be marked by another person (teacher or peer). Course creators can add content directly to a course.

Scores/results from use of H5P and other content will be available within the progress overview screen.
