### ISSUE TITLE
Student user able to add a new course || Permission issue || Noted on Web app

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#713]
**Describe the bug**
A student user able to create a new course

**To Reproduce**
1. Login as a student user
2.On course page +Course button is available to create new course

**Expected behavior**
Student user should not have permission to add a new course. Student should not able to view the +Course button

**Screenshots**
![Screenshot from 2023-11-21 12-45-53](https://github.com/UstadMobile/UstadMobile/assets/78338755/5949be4d-ffe3-4c4c-a77f-871d9db50fac)

**Comment by mikedawson** [comment]
@poojaustad I think this is fixed with the above commit on dev-mvvm-primary. Please check / confirm when the Jenkins build comes out.

**Comment by poojaustad** [comment]
Tested. This issue has been fixed. closing this issue
