### ISSUE TITLE
Toggles not working on the Assignment page. When the toggle is off mode students able to view the private/course comment fields || MVVM_Primary

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#714]
Describe the bug
Toggles not working on the Assignment page. When the toggle is off mode students able to view the private/course comment fields

To Reproduce

Go to edit a course 
Add/edit an assignment
Try to change the toggles

1.  Allow class comments from students
2. Allow private comments from students

Expected behavior
When the toggle is off mode students should not able to view the private/course comment fields

Screenshots
[Screencast from 11-22-2023 12:04:13 PM.webm](https://github.com/UstadMobile/UstadMobile/assets/78338755/3c1f2bcf-b87a-4870-a1a8-d3700e31e253)

**Comment by mikedawson** [comment]
@poojaustad  I think this is fixed as per the above commit. Please check.

**Comment by poojaustad** [comment]
This issue got fixed, thanks @mikedawson
