### ISSUE TITLE
Timezone issue noted on Assignment deadline || Noted in webapp

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#715]
**Describe the bug**
The selected deadline and save deadline time is not matching due to timezone issue

**To Reproduce**
1. Go to 'Assignment edit page and add deadline date and time as eg: 23/11/2023 1pm
2. Save assignment and course 
3. When user open the assignment page - deadline is visible as - 23/11/2023 5pm (Asia/Dubai)

**Expected behavior**
The selected deadline and saved deadline time should match

**Screenshots**
![Screenshot from 2023-11-22 13-03-19](https://github.com/UstadMobile/UstadMobile/assets/78338755/7f44216a-0671-4148-b6bc-304f7c3023ef)
![Screenshot from 2023-11-22 13-02-56](https://github.com/UstadMobile/UstadMobile/assets/78338755/f80a5998-324c-4af3-8ee2-8fee7246ca3c)

**Comment by mikedawson** [comment]
@poojaustad I think this is fixed with the above commit.

**Comment by poojaustad** [comment]
This issue has been fixed. Tested
