### ISSUE TITLE
Ability for administrators to moderate discussion board content

### ISSUE THREAD

**Issue by gravitz** [UstadMobile/UstadMobile#733]
Moderation support for administrators to remove inappropriate content, enable/disable discussion board etc

Traceability
UstadMobile's Technical proposal

**Comment by mikedawson** [comment]
Teachers and admins can add and remove discussion board(s) from a course. If they don't want any discussion boards on a class, then they just don't add any discussion boards to the course. Admins and teachers can add multiple discussion boards (e.g. for different topics, modules, etc) as they wish.

Admin moderation was not part of any previously release and was previously handled manually (through database administration/SQL).

I can see the potential use case for this to ensure that an admin user or teacher could respond quickly to someone posting an inappropriate comment. This could be plugged into an existing milestone somewhere (not 2.2.3 which only covers porting existing functionality to MVVM, but one of the others). I would suggest further discussion on how to handle that.

**Comment by mikedawson** [comment]
Now available with version 0.4.97 @mhdosman @komil-pro
