### ISSUE TITLE
Support for 3 languages (Tajik, Russian and English on the platform's interfaces

### ISSUE THREAD

**Issue by gravitz** [UstadMobile/UstadMobile#735]
UI translation across the different interfaces (web, mobile and desktop) in Tajik, Russian and English.

Traceability
Contract Amendment 2 (PO43334215 )

**Comment by mikedawson** [comment]
All components already support the above three languages (and a few others). I have added Language supports items to the [checklist under section 12](https://github.com/UstadMobile/UstadMobile/blob/dev-mvvm-primary/test-end-to-end/README.md).

I have already implemented and tested language switching on all three platforms. This will be put into the dev-mvvm-primary branch very shortly.

**Comment by mikedawson** [comment]
This is already implemented.
