### ISSUE TITLE
BLOCKER || Mvvm Primary || Webapp || The SAVE button not working as expected on the personEditView page

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#747]
**Describe the bug**
The SAVE button not working as expected on the personEditView page. When user click on Save button the user remains on same page

**To Reproduce**
1. Go to People tab
2. Click on +Person button
3. Enter user details and click on - no actions visible as expected

**Expected behavior**
On the personEditView page, When the user clicks on the Save button the user details gets save and direct to user details page

**Screenshots**
![Screenshot from 2023-11-27 09-26-06](https://github.com/UstadMobile/UstadMobile/assets/78338755/794b3024-bb6c-4dab-a144-6b44a8560dff)

**Comment by mikedawson** [comment]
Fixed with commit [cd91c073f90c5c621e4c75773dd5d70a2292e32e](https://github.com/UstadMobile/UstadMobile/commit/cd91c073f90c5c621e4c75773dd5d70a2292e32e)
