### ISSUE TITLE
Links in EPUB content are not handled as expected

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#76]
**Describe the bug**
When the user clicks a link in an EPUB it should either (go to that page in the epub and advance the pager) or open a browser window. 

**To Reproduce**
1. Go to any epub source (e.g. African Storybook), Pratham
2. Download and open an EPUB
3. Click on any internal or external link

**Expected behavior**
External links should start the system browser. Internal links (eg. to another chapter) should advance the pager.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: All Android

**Smartphone (please complete the following information):**
 - Device: Nokia 2.1
 - OS: Android 9

**Additional context**
N/A

**Comment by poojaustad** [comment]
This issue has been fixed. Tested on Redmi 6A device. Android  version -8.1
