### ISSUE TITLE
Mvvm-primary || Course-Terminology is not working as expected

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#769]
**Describe the bug**
On the course edit page, On the Terminology field user can add new terminolgy for Teacher and Student . When user change terminology and save it, the default terminologies should change to newly added one. 

**To Reproduce**
1. Go to Course edit page
2. Click on Terminology field
3. click on " Add new terminology'
4. enter new terminology for teacher and student then save

**Expected behavior**
On the course edit page, On the Terminology field user can add new terminolgy for Teacher and Student . When user change terminology and save it, the default terminologies should change to newly added one. 

**Screenshots**
[Screencast_terminology.webm](https://github.com/UstadMobile/UstadMobile/assets/78338755/6d3a34fd-c307-478a-9f01-53853f845143)

**Comment by mikedawson** [comment]
Hi @poojaustad I think this is resolved now. Please verify, and if everything is resolved, please close the issue. Thanks.

**Comment by mikedawson** [comment]
I think this issue should be closed. Course list is also updated as per screenshot

![Screenshot from 2024-01-09 17-41-48](https://github.com/UstadMobile/UstadMobile/assets/4280622/ab3066d2-3c11-4e4e-aaf2-8827ad638837)

**Comment by poojaustad** [comment]
Verified. Fixed
