### ISSUE TITLE
Mvvm primary || Webapp || Username should be unique, duplication should be reported as an error. Currently 2 people can create same username.

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#772]
**Describe the bug**
Username should be unique. Currently 2 people can create same username.

**To Reproduce**
1. Go to people page
2. Click on +Person
3. add details and save
4. click on 'create account' button and add same username of another user and click save. Data gets saved without any error

**Expected behavior**
Username should be unique, duplication should be reported as an error. 

**Screenshots**
[Screencast from 12-13-2023 03:42:15 PM.webm](https://github.com/UstadMobile/UstadMobile/assets/78338755/7611a2c5-2f9a-404d-b7df-9383c20b5279)

**Comment by mikedawson** [comment]
Now implemented.

![Screenshot from 2023-12-19 09-59-22](https://github.com/UstadMobile/UstadMobile/assets/4280622/e6c43039-f2f8-4508-a36d-a5a06a92f310)
