### ISSUE TITLE
Mvvm Primary || When parent copy-paste the parental consent link on incognito window and register - user not able to see consent button

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#773]
**Describe the bug**
When parent copy-paste the parental consent link on incognito window and register - user not able to see consent button

**To Reproduce**
1. The Student aged below 13 registered in web app
2. The parent received the email after registration
3. Parent copy-paste the link in the email on the new incognito window
4. Parent creates and account then the parent consent message appears but the relationship field and consent buttons are not visible

**Expected behavior**
When parent copy-paste the parental consent link on the incognito window and register- user able to view consent button

**Screenshots**
![Screenshot from 2023-12-18 13-50-37](https://github.com/UstadMobile/UstadMobile/assets/78338755/f99b0975-2f89-41bb-b31a-7b24c4936a10)

**Comment by mikedawson** [comment]
I could not reproduce this. I opened the link received in a new incognito window. Please double check that this was the latest mvvm-primary. 

[Screencast from 2023-12-19 09-33-50.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/14350340-bec2-4999-b353-ae4b8f3d635c)

**Comment by poojaustad** [comment]
I was not able to reproduce this issue. Closing.
