### ISSUE TITLE
Mvvm Primary || On the registration page , when user gets an error saying the password field is required, and when the user enters value, the error is not disappeared

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#779]
**Describe the bug**
On the registration page , when user gets an error saying the password field is required, and when the user enters value, the error is not disappeared

**To Reproduce**
1. Go to Registration page
2. leave password field blank and Click on register button
3. **This field is required** error appears just below the password field
4. When user enter the password still the error is visible

**Expected behavior**
On the registration page , when user gets an error saying the password field is required, and when the user enters value, the error should disappear

**Screenshots**
![Screenshot from 2023-12-28 15-45-42](https://github.com/UstadMobile/UstadMobile/assets/78338755/48bbfdac-38c2-4405-8608-4c735ca9c76c)

**Comment by mikedawson** [comment]
Fixed with above referenced commit

[Screencast from 2024-01-09 19-50-12.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/a629edb9-02c8-473a-9b1a-b294047c988f)

**Comment by mikedawson** [comment]
@poojaustad  please verify and close if this is now resolved, thanks.

**Comment by poojaustad** [comment]
Verified, fixed.
