### ISSUE TITLE
Mvvm Primary || Web app || Discussion post is not getting saved in discussion block

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#782]
**Describe the bug**
The post added under a discussion board is not getting saved

**To Reproduce**
1. Go to the course dashboard 
2. Click on '+Post' and add post and save
3. Open the web app  in a new incognito window and open the course discussion board
4. The added post is not visible on the discussion board

**Expected behavior**
The post added under a discussion board should get saved

**Screenshots**
![005_005_user_add_external_links_to_post -- Teacher able to add external link as reply to the post (failed)](https://github.com/UstadMobile/UstadMobile/assets/78338755/77cf9d37-dd0d-44b9-8440-e5eca1fef0b6)

**Comment by mikedawson** [comment]
Fixed with commit https://github.com/UstadMobile/UstadMobile/commit/019da1330a60daf6b0bb715ac46d831592bd036f
![Screenshot from 2024-01-03 16-47-15](https://github.com/UstadMobile/UstadMobile/assets/4280622/c5bf4aed-9a1e-4d3d-b308-48b58f4d993b)
