### ISSUE TITLE
Crash happened on clicking on join existing courses

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#784]
Describe the bug
Crash happened on clicking on join existing course in Courses  page

To Reproduce

Go to Courses  Tab on the application
Click on the Course + button,
It crashes

Expected behavior
to open a new view to list the existing courses

Screenshots

https://github.com/UstadMobile/UstadMobile/assets/153509442/6a0f244e-aabb-485c-9cce-289363a61e6f

Smartphone (please complete the following information):

Device: Samsung A53

**Comment by mikedawson** [comment]
Hi - thank you for noting this. That screens isn't in the APK or web version at the moment, will be added when Android/Desktop content is completed. This is tracked here: https://github.com/UstadMobile/UstadMobile/issues/617
