### ISSUE TITLE
Full screen video on Android is not 100% full screen

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#789]
**Describe the bug**

Entering full-screen mode does not make the video 100% full screen.

**To Reproduce**
1. Go to library
2. Upload a video
3. Open the video
4. Play it on Android
5. Click full screen

**Expected behavior**
Should be entirely full screen, no edges

**Screenshots**
![Screenshot from 2024-01-17 14-55-36](https://github.com/UstadMobile/UstadMobile/assets/4280622/5bc8dc3b-ffd0-4389-befc-9fcd08fba23b)

**Comment by mhdosman** [comment]
I think we can pass this to the next release after finishing all current milestones, it is okay now working well, in the next  release we can consider this

**Comment by mikedawson** [comment]
Fixed since version 0.4.117
