### ISSUE TITLE
Uploading files with non English names (cyrilic, etc non ISO 8859-1) fails with error message

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#791]
**Description**
When uploading files with non English names (Cyrillic, etc. non ISO 8859-1) fails with error message:
Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.

**Expected behavior**
It is expected, that files with non-English names will be uploaded too.

**Screenshots**
Attached.
![Uploading filename_issue_uploading_file.jpg…]()

**Desktop (please complete the following information):**
 - Browser Google Chrome
 - Version 120.0.609.217

**Comment by mikedawson** [comment]
I think this is now resolved. @komil-pro  can you please check, confirm, and close the issue if fixed.

[Screencast from 2024-01-17 23-40-01.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/1ef50371-4f41-4474-8edd-85f0dc1d4cc8)

**Comment by komil-pro** [comment]
Check. Now it works.
