### ISSUE TITLE
Issue when changing password of existing user by admin (testing on 17.01.2024)

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#792]
**Describe the bug**
Issue when changing password of existing user by admin (testing on 17.01.2024)

**Expected behavior**
The password should change or get an error message.

![Uploading existing user change pwd.jpg…]()

Web version

**Comment by mikedawson** [comment]
Hi,

Thank you for reporting this. It is fixed in version 0.4.10. 

[Screencast from 2024-01-19 12-48-19.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/5d96cc6f-8cb0-4d40-a35d-fbde7e7d6bdb)

**Comment by komil-pro** [comment]
The issue has been resolved.
