### ISSUE TITLE
Usability Issue, Fields are not clear

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#794]
**Describe the bug**
Input Fields are not clear, too much dark

**To Reproduce**
1. Go to Course 
2. Go to TEST 17.01.2024 course
3. Scroll down to Module 2 test
4. Choose Group asssignment
5. 5. Try to add comment

**Expected behavior**
The input field should be clear for the user to enter the input.

**Screenshots**
![WhatsApp Image 2024-01-17 at 15 32 04_c23b2dcb](https://github.com/UstadMobile/UstadMobile/assets/153509442/934cad14-601b-4531-9d6b-0bd4d5e7d36a)

**Smartphone (please complete the following information):**
 - Device: Samsung A53
 - OS: Android 13
on the android app

**Comment by mikedawson** [comment]
Hi @mhdosman  - I think this is fixed now as per the screenshot below. 

![Screenshot from 2024-01-18 15-22-11](https://github.com/UstadMobile/UstadMobile/assets/4280622/ae6d8928-ae1d-4d64-9262-fe6dad80ba61)

**Comment by mhdosman** [comment]
it is strange still have it on my device, on add a class comment
![WhatsApp Image 2024-01-18 at 14 52 31_60d60bd2](https://github.com/UstadMobile/UstadMobile/assets/153509442/7c1f52c7-36b7-4ee7-b95c-609fbc31af01)

**Comment by mikedawson** [comment]
The build is pending on the server, this fix is in version 0.4.6. I have added the version info to the login screen and account list screen. Will be available after some minutes.

**Comment by mikedawson** [comment]
Now deployed.
