### ISSUE TITLE
Usability Issue, Description Field is not clear : Add a new post in  a discussion

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#795]
**Describe the bug**
Usability Issue, Fields are not clear : Add a new post in  a discussion

**To Reproduce**
1. Go to Go to Course
2. Click on  TEST 17.01.2024 course
3. Choose discussion Test
4. Click add new post

**Expected behavior**
The input field should be clear for the user to enter the input.

**Expected behavior**
The input field should be clear for the user to enter the input.

**Screenshots**
![WhatsApp Image 2024-01-17 at 15 35 37_d7d4f63b](https://github.com/UstadMobile/UstadMobile/assets/153509442/71f3c523-5076-404b-aedc-783d4228c68b)

**Smartphone (please complete the following information):**
 - Device: Samsung A53
 - OS: Android 13
on the android app

**Comment by mikedawson** [comment]
I think this is resolved in version 0.4.8 (APK available now dev-mvvm-primary-maktab build 25).

[Screencast from 2024-01-18 17-15-11.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/1cd9a63b-1c92-4768-9163-b229e3e72975)

**Comment by mhdosman** [comment]
I am still thinking if the field has some kind of border it would be better, for some users like this it would be confusing if the user is not seeing a clear field to fill

**Comment by mikedawson** [comment]
I would recommend divider line - similar to what is used in the Gmail app. 

Making a border that would look like what Android uses on other "normal" (e.g. non-formatted) textfields is surprisingly complex. All of that logic is in internal / private classes, not readily usable on its own without the "normal" textfield. 

Can we go ahead with the divider line?

**Comment by mhdosman** [comment]
I think it would work, you might give it a try and let’s see,
