### ISSUE TITLE
After updating the password of a user as an admin, no indication that if the operation is done

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#796]
**Describe the bug**
After updating the password of a user as an admin, no indication that if the operation is done

**To Reproduce**
1. Go to People
2. Choose a user
3. Click change a password
4. enter password and then click save

**Expected behavior**
Some indicator that the password has been changed successfully and getting back to the people page in the applicatoin

**Screenshots**
<img width="951" alt="image" src="https://github.com/UstadMobile/UstadMobile/assets/153509442/62545f8f-1066-41b8-bb96-41235d1eabfb">

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser: Chrome 
 - Version 120

**Comment by mikedawson** [comment]
Hi,

Thank you for reporting this. Version 0.4.10 shows a Snackbar notification when the password is successfully changed, or an error message if any error occurs.

[Screencast from 2024-01-19 12-48-19.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/5fd6db7d-a5f1-4706-8d3d-f49f0902980a)
