### ISSUE TITLE
The contrast in the Edit Course Screen needs to be improved to ensure that users can easily distinguish the elements

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#797]
**Describe the bug**

**To Reproduce**
1. Go to Courses
2. Click on a course
3. Click on Edit Button
4. You see the screen has some titles with color black not clear to the user, 

**Expected behavior**
The screen should use colors with high contrast to ensure that the user can easily distinguish them

**Screenshots**
![WhatsApp Image 2024-01-18 at 10 25 31_a3f23350](https://github.com/UstadMobile/UstadMobile/assets/153509442/08f5898b-c4c9-48f2-a8a9-e5d159634410)

**Smartphone (please complete the following information):**
 - Device: Samsung A53
 - OS:Android 13

**Comment by mikedawson** [comment]
![Screenshot from 2024-01-18 13-16-32](https://github.com/UstadMobile/UstadMobile/assets/4280622/1f845db2-1727-49ac-8cea-27541e091313)



Dark mode was not being applied properly to these items: I believe this is now fixed. @mhdosman  can you please check, confirm

**Comment by mhdosman** [comment]
yes thank it is fixed now,
still a small issue in another screen I don't want to open an issue for it,
![WhatsApp Image 2024-01-18 at 12 21 02_638c8c91](https://github.com/UstadMobile/UstadMobile/assets/153509442/f06dc8c8-81a8-4450-a111-051b5b84ff09)
you can see it in the screen shot

**Comment by mikedawson** [comment]
![Screenshot from 2024-01-18 15-24-44](https://github.com/UstadMobile/UstadMobile/assets/4280622/8c540394-84cc-497a-8c7b-aa14736dda61)

I think you're referring to the icons here. That is fixed in version 0.4.6
