### ISSUE TITLE
Modules in  that have not yet reached their due date are not visible to the admin

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#798]
**Describe the bug**
In a course, if the teacher has added a module with due date later, the admin user is not able to see those modules

**To Reproduce**
0.Login as a teacher
1. Go to Courses, choose a course (TEST 17.01.2024)
2. Click on Edit, add module(Module 3 has been added, you can add Module 4), change due date to a later date, and save
3. Login with  an admin account
4. Go to the same course

**Expected behavior**
Admin should be able to see and edit all the courses regardless their due date

**Smartphone (please complete the following information):**
 - Device: Samsung A53
 - OS: Android

**Comment by mikedawson** [comment]
@mhdosman this is the expected (correct) behavior. This field is the hide until date (not a due date) which allows teachers and admins to layout their course in advance by hiding content until a given date.

Content which is hidden until after a specific date is hidden on the detail screen ( e.g. main course screen) for all users. Teachers and admins see the same layout that students will see. The hidden content is visible when going to edit.

I can see a use case for allowing the teacher/admin to see those modules so they can enter a module/assignment etc and see how everything looks within the assignment etc. We would need to have a "show hidden modules" option for teachers/admin.

[Screencast from 2024-01-18 13-30-05.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/5ea716dc-21c2-4375-8aab-342e7870542d)
