### ISSUE TITLE
Modules in that have not yet reached their due date are not visible to the user who created it

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#799]
Describe the bug
In a course, if the teacher has added a module with due date later, the admin user is not able to see those modules

To Reproduce

Login as a teacher or an admin
Go to Courses, choose a course (TEST 17.01.2024)
Click on Edit, add module(Module 3 has been added, you can add Module 4), change due date to a later date, and save
Go to the same course
The due date in the future item is not shown.

Expected behavior
The creator of a module with a due date in the future should be able to view and edit the module, regardless of the due date

Smartphone (please complete the following information):
Device: Windows 11
OS: Chrome 120

**Comment by mikedawson** [comment]
Hi I think this is mostly the same as issue #798  - @mhdosman can we please close this issue and track it using issue 798?

**Comment by mhdosman** [comment]
I think it should be visible to the user that she/he created an item here and it has future due date, with some mark, 
the teacher/ admin should not need to enter the edit mode of the course to see future due date items,

**Comment by mhdosman** [comment]
but anyways if this will take time,  and time  now is very precious and should be spend on the milestones with the highest priority, I can close this,

**Comment by mikedawson** [comment]
I think it's not the highest priority, but it's a valid point. I wouldn't close it. I've labeled it as P3 (e.g. not-a-blocker).
