### ISSUE TITLE
Future due date assignment is not visible to student even after its due date 

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#801]
Login as a student who enrolled in the course and was assigned to the assignment, but the assignment is not visible to the user.
Tried from many browser, cache free browsers, hidden mode

**Comment by mikedawson** [comment]
I was able to reproduce this issue. Will be fixed shortly.

**Comment by mikedawson** [comment]
Thank you for reporting this. It has been fixed in version 0.4.9. Probably something we will add to the end-to-end test list.

[Screencast from 2024-01-18 19-58-26.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/c8f9c44d-db23-4777-b4c6-7e66764e43bd)
