### ISSUE TITLE
Usability Issue: he user has to press the back button on the browser menu (backspace) to return to the course and complete the item where they left off, as there is no ‘back to course’ button in the menu.

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#803]
**Describe the bug**
he user has to press the back button on the browser menu (backspace) to return to the course and complete the item where they left off, as there is no ‘back to course’ button in the menu.

**To Reproduce**
1. Go to Course
2. Click on a course item
3. Try to get back to where you were

**Expected behavior**
To return to the item where the user left off, the user must use the back button on the browser menu (backspace) as there is no ‘back to course’ button or ‘next’ button in the menu.

**Screenshots**
<img width="952" alt="image" src="https://github.com/UstadMobile/UstadMobile/assets/153509442/ea93d388-a93f-4cff-81bd-ba03b4f2b9ae">

**Desktop (please complete the following information):**
Windows Chrome

**Comment by mikedawson** [comment]
Hi,

I think this is an interesting UX question. A few things might be worth considering here:

- Use [breadcrumbs](https://mui.com/material-ui/react-breadcrumbs/) on the web - e.g. so it shows Courses /  Course Name / (Module Name if any) / Course Block title. I have not seen breadcrumbs used on mobile.
- Keep the course title as the main title at the top, then put the course block title as a heading in the 'main body' area. This way the user has some extra "context" about where they are
- In course content, it's quite likely you don't want to go back to the course itself, but after reading that item, you want to go to the next or previous item in the course.

I think this isn't really a bug, but a UX question that should be considered for future development. That UX change would likely be significant, so should involve some testing ideas with users before implementation.

For now, I would hope that users will be able to use the browser back button.

**Comment by mhdosman** [comment]
As we don't have enough time, and the app is basically will be used from Mobile and Tablet, I am gonna close this.
