### ISSUE TITLE
Import content from link fails

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#804]
**Describe the bug**
Adding content (eg PDF etc) using a plain HTTP link

**To Reproduce**
1. Go to content
2. Click add content, then import from link
3. Use a valid plain http link to a supported file e.g. PDF
4. See error message: invalid link

**Expected behavior**
Should add content from the link

**Screenshots**

![err-add-from-link](https://github.com/UstadMobile/UstadMobile/assets/4280622/c16bbd15-921f-4ad5-871e-5f49e9e45d2d)

**Comment by mikedawson** [comment]
This is fixed in version 0.4.12:

[Screencast from 2024-01-21 00-01-19.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/b1d3af26-f170-43c0-941d-f233dc6028e9)

**Comment by mikedawson** [comment]
Also fixed on Android:

https://github.com/UstadMobile/UstadMobile/assets/4280622/2b20a9ba-cc3a-4ceb-b17d-260208605b03

**Comment by mhdosman** [comment]
it worked fine except epub, if you provide me with ePub example that worked with you, anyway I think this can be closed even if it is not working with ePub files

**Comment by mikedawson** [comment]
It should work with any valid EPUB2/EPUB3 file that is accessible on plain HTTP. We have tested that. @mhdosman  Can you please provide the example of a link that doesn't work?

**Comment by mhdosman** [comment]
this one, I was not able to import it, using the mobile app
https://github.com/IDPF/epub3-samples/releases/download/20230704/childrens-literature.epub

**Comment by mikedawson** [comment]
![Screenshot from 2024-02-20 17-38-27](https://github.com/UstadMobile/UstadMobile/assets/4280622/10c0046e-b829-412e-937c-1848800716a1)

The link is using a http redirect, which is not supported. That would probably explain the issue. 

We have epubs and other files on plain http here:

https://www.ustadmobile.com/files/tmp-contentfiles/

**Comment by mhdosman** [comment]
using your link I was able to import ePub contents, I guess this can be closed
