### ISSUE TITLE
Content cannot be deleted from device

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#805]
**Describe the bug**
Content cannot be deleted from device

This issue is not reproducible. Downloading, then removing content seem to function as expected.

https://github.com/UstadMobile/UstadMobile/assets/4280622/ed12a8b8-26e3-45a1-bc4a-805e4f42cc4f

**Comment by mhdosman** [comment]
I think this can be closed, it was for an older version of the app
