### ISSUE TITLE
Indenting course blocks on mobile app fails

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#807]
**Describe the bug**
Indenting course blocks on mobile version fails

**To Reproduce**
1. Go to add or edit a course
2. Create a block (e.g. text)
3. Click three dots, next to block, then click indent
4. Note the block does not indent as expected.

**Expected behavior**
Should indent/unindent. Menu should hide again after being clicked.

**Screenshots**

https://github.com/UstadMobile/UstadMobile/assets/4280622/1eb0280f-25fc-4730-a8b9-41dbb65599aa

**Comment by mikedawson** [comment]
Fixed in version 0.4.13

https://github.com/UstadMobile/UstadMobile/assets/4280622/ba929994-d3ec-4e76-9ba1-283263631f39

**Comment by mhdosman** [comment]
it is working, you can close this
