### ISSUE TITLE
Private comments reported as visible by other users

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#808]
**Describe the bug**
Private comments reported as visible by other users

**To Reproduce**
Not able to reproduce

**Expected behavior**
Private comments on assignment should be visible only between teacher and student.

**Screenshots**

[private-comments-video.zip](https://github.com/UstadMobile/UstadMobile/files/13997925/private-comments-video.zip)  - Video M4V in zip

**Comment by mhdosman** [comment]
You can close this, tested in 0.4.84
