### ISSUE TITLE
Private comments reported as visible for others in group assignment

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#809]
**Describe the bug**
Private comments reported as visible for others in group assignment

**To Reproduce**
Currently not able to reproduce

**Expected behavior**
When an assignment is completed by groups, then private comments should be visible for other students in the same group and the teacher.  

**Screenshots**

https://github.com/UstadMobile/UstadMobile/assets/4280622/840e5c62-4ed1-44d0-b46b-bf9e27bfe694

**Comment by mhdosman** [comment]
This can be closed, tested on 0.4.84
