### ISSUE TITLE
Private comments on assignment reported as visible by other users on web version

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#811]
**Describe the bug**
Private comments on assignment reported as visible by other users on web version

**To Reproduce**
Not able to reproduce

**Expected behavior**
Private comments on assignment should be visible by the student and their teacher/admin

**Screenshots**
[Screencast from 2023-11-16 23-26-32.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/74216685-cff3-49cf-8479-ef09375c74f7)

**Comment by mhdosman** [comment]
@mikedawson  you can close this, the private comments are visible to admin/teacher now
