### ISSUE TITLE
EPUB does not open on mobile devices (Android)

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#813]
**Describe the bug**
EPUB does not open on mobile devices (Android version)

**Screenshots**
![EPUB_opening_issue_Android](https://github.com/UstadMobile/UstadMobile/assets/60223648/0525188a-2b64-43e2-89d2-2e99a4a7b994)

**Desktop (please complete the following information):**
 - OS: Android

**Comment by mikedawson** [comment]
This looks like an older version of the app. Please make sure the version is 0.4.14 or higher (you can check in the account list screen).

**Comment by komil-pro** [comment]
In version 0.4.14 has been resolved. This issue will be closed.
