### ISSUE TITLE
As a student while  downloading a resource the Cancel button is not working,

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#823]
**Describe the bug**
As a student while  downloading a resource the Cancel button is not working,

**To Reproduce**
1. Go to Courses
2. Click on Unicef course
3. Scroll down to PDF Test file and click on it
4. Start downloading the file,
5. click stop it is not respondig

**Expected behavior**
To stop downloading when it is clicked on it,

**Screenshots**
<img width="950" alt="image" src="https://github.com/UstadMobile/UstadMobile/assets/153509442/9d4764dd-7b52-46d2-b89b-e02aa757cf4e">

**Desktop (please complete the following information):**
 - OS:Win 11
 - Version : v0.4.51

**Comment by mikedawson** [comment]
Hi this hasn't been implemented yet as per the milestone tracker: https://github.com/UstadMobile/UstadMobile/issues/612

Hence the cancel button doesn't apply yet. This should be implemented by tomorrow.
