### ISSUE TITLE
Record Attendance at a future date : I was able to record attendance at a future date

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#825]
**Describe the bug**
I was able to record attendance at a future date

**To Reproduce**
As an admin or a teacher
1. Go to Courses
2. Click on Attendance tab
3. Create attendance at a future date ( a weeks later for example)
4. It is created successfully

**Expected behavior**
Preventing the user from creating an attendance at later times

**Screenshots**
<img width="953" alt="image" src="https://github.com/UstadMobile/UstadMobile/assets/153509442/0989102e-4213-407c-9194-f7685ba3b95a">

**Desktop (please complete the following information):**
 - Win 11 pro
 - 0.4.51

**Comment by mikedawson** [comment]
Blocking the recording of post-dated attendance never made it onto any validation list or spec that I'm aware of. 

It was easy enough to change, so it's been updated in version 0.4.59

![Screenshot from 2024-02-07 23-24-18](https://github.com/UstadMobile/UstadMobile/assets/4280622/caea32e8-2d7c-4fae-8c31-f417b003a15d)

@mhdosman can you please check this with version 0.4.59, and if it is resolved, please close this issue. If there is anything unresolved, please add a comment.
