### ISSUE TITLE
In the form of adding text block in a course: Input for description of a text in the course is only one line, should be larger.

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#826]
**Describe the bug**
In the form of adding text block in a course: Input for description of a text in the course is only one line, should be larger.

**This is not a bug but an improvement to the UI,** 
**To Reproduce**
As an admin or teacher
1. Go to any Course
2. Click on edit
3. Add module choose text block
4. You can see that the description field in only one line.

**Screenshots**
<img width="957" alt="image" src="https://github.com/UstadMobile/UstadMobile/assets/153509442/6c324814-ea9e-4937-b7c8-bca6932a939b">

**Desktop (please complete the following information):**
Win OS / version 0.4.51

**Comment by mikedawson** [comment]
The text field did automatically expand when the user typed, but I see the point that it could confuse users. This has been updated in version 0.4.59. 

![Screenshot from 2024-02-07 22-22-52](https://github.com/UstadMobile/UstadMobile/assets/4280622/ab34aae4-a123-43fa-bbde-db424786918c)

@mhdosman can you please check this in version 0.4.59. If resolved, please close this issue. If not resolved, then please add a comment.
