### ISSUE TITLE
Student can submit assignment (text and attachment) - testing task 4.2 - currently only text can be submitted, not attachment.

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#831]
**Describe the bug**
Currently only text can be submitted, not attachment.

**Screenshots**
![Uploading student can submit assignment_no attachment.png…]()

**Comment by mikedawson** [comment]
Correct - this isn't implemented yet (as per https://github.com/UstadMobile/UstadMobile/issues/762 ), should be online around the end of today.

**Comment by mikedawson** [comment]
@komil-pro I think this is now completed with version 0.4.97, can you please check and close this issue if so. or comment if there is anything remaining? Thanks

**Comment by komil-pro** [comment]
Confirm, that not only text but attachments now available.
