### ISSUE TITLE
Issue with opening EPUB in version 0.4.66 of the Android App

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#837]
**Describe the bug**
Issue with opening EPUB in version 0.4.66 of the Android App
Some error showing instead of the epub content, please see screenshot.

![issue_with_opening_epub_mobile_v 0 4 66](https://github.com/UstadMobile/UstadMobile/assets/60223648/9e8a55ee-6706-4ab8-949b-1b07416bdf72)

**Comment by poojaustad** [comment]
Dear Komil,

I tried testing the same version app but didn't reproduce this issue. Can you please upload the epub file you used to try and reproduce the bug?

Screenrecord
[Screencast from 02-12-2024 04:40:18 PM.webm](https://github.com/UstadMobile/UstadMobile/assets/78338755/7099aab0-e411-4a38-a929-d9a479c2cdd9)

**Comment by mikedawson** [comment]
I'm not sure if this is related to the version, but I see the same issue when using the staging server with a given content entry ( /umapp/#/ContentEntry?entityUid=558289358288039936 )

**Comment by mikedawson** [comment]
@komil-pro  this has been fixed in version 0.4.73 . This was also influenced by issues referenced in issue #840 .

[Screencast from 2024-02-16 18-12-49.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/c913fbb8-a0c4-4f78-b1b7-569824146d55)

**Comment by komil-pro** [comment]
Checked on mobile app v. 0.4.76 (300), it is working.
