### ISSUE TITLE
a user friendly message after the admin accepts a user requested to join a class using invite link

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#850]
**Describe the bug**
After a user requests to join a class using an invite code, and the admin accepts a user friendly message should be display for a few seconds before disappearing

**To Reproduce**
1. As a user Get a valid invite code to join a class
2. Click on join a class, enter the invite code and request to join
3. Login as an admin go to that course and see second tab people
4. accept the request from the user and see the message

**Expected behavior**
A clear user friendly message should be displayed that the user has been enrolled successfully and can access the course now.

**Screenshots**

https://github.com/UstadMobile/UstadMobile/assets/153509442/22907f98-a910-4187-88ea-706a14c188b1

**Smartphone (please complete the following information):**
 - Device: Samsung A53

 - Version 0.4.85 (309)

**Comment by mikedawson** [comment]
@mhdosman the issue here is only that the text is wrong e.g. it is showing %1$s instead of the student name, right?

**Comment by mhdosman** [comment]
Exactly updating this %1$s to something readable is enough

**Comment by mikedawson** [comment]
@mhdosman this is now fixed in version 0.4.86 . Can you please check and close if resolved, or comment if you think there is anything else that needs done on this issue? Thanks.

![Screenshot from 2024-02-28 19-13-33](https://github.com/UstadMobile/UstadMobile/assets/4280622/53d89e79-bb04-4e01-9ed0-4aed430e5f50)

**Comment by mhdosman** [comment]
fixed thanks
