### ISSUE TITLE
Changing language from setting, the app is restarting and infinitely loading

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#852]
**Describe the bug**
Changing language from setting, the app is restarting and infinitely loading

**Expected behavior**
to restart the app in the desired language successfully

**Screenshots**
https://github.com/UstadMobile/UstadMobile/assets/153509442/71378980-3b57-4f7e-bc2f-40a6d553d6aa

**Smartphone (please complete the following information):**
 - Device: Samgsung A53
 - Ios : andoird 12

**Comment by mikedawson** [comment]
This doesn't reproduce for me (tested on Android 10 and 12 as per videos below). 

Android 10:
https://github.com/UstadMobile/UstadMobile/assets/4280622/bdbaf966-da42-45d0-ae56-4814999949de

Android 12:
https://github.com/UstadMobile/UstadMobile/assets/4280622/d2b42e86-b29a-4b59-b09b-f67136a51724

@mhdosman can you please mention what is your system language on the device where you took the video?

**Comment by mikedawson** [comment]
@poojaustad was able to reproduce this issue. We are using the Process Phoenix library to run the restart, which we didn't have any issues with before. 

I have added a 5 second timeout. If the restart fails (e.g. does not restart within 5 seconds), then we will show a dialog as below.

![close_now](https://github.com/UstadMobile/UstadMobile/assets/4280622/0c957361-9b17-4f4b-9e60-a44918978b66)

**Comment by mikedawson** [comment]
The manual restart workaround is now implemented in version 0.4.86 . 
@mhdosman can you please check and close this if resolved, or comment if there is anything else that you think needs done?
