### ISSUE TITLE
crash on clicking permissions on permission on course page

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#857]
**Describe the bug**
crash on clicking permissions on permission on course page

**To Reproduce**
1. Go to course page as admin/teacher
2. Click on permission page
3. It creashes

**Screenshots**

https://github.com/UstadMobile/UstadMobile/assets/153509442/96eb9fd4-a961-4bba-99ce-750e8259a82b

**Smartphone (please complete the following information):**
 - Device: , samsung a53, 
 - version: 0.4.88 (312)

**Comment by mikedawson** [comment]
@mhdosman this is now fixed in version 0.4.90 . Can you please check, and close the issue if it is resolved, or comment if there is anything else remaining? Thanks.

**Comment by mhdosman** [comment]
It is fixed in version 0.4.90, thanks
