### ISSUE TITLE
Issue noted on Cypress || web-app || Course comments added by a teacher are not visible to students in one group. 

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#860]
**Describe the bug**
Course comments added by a teacher are not visible to students in one group. Noted in cypress test. 

note: This is not reproduced manually

**To Reproduce**
1. Run cypress test - WEB_004_008_group_users_add_assignment_and_course_comments.cy.js
2. There are two assignment groups Group 1 and Group 2
3. Group 1 adds assignments and add course comments, teacher adds course comment
4. Group 2 students are not able to see the teacher's comment in the course comment list

**Expected behavior**
Course comments should be visible to students and teachers enrolled in a course

**Screenshots**
![Screenshot from 2024-03-19 12-43-43](https://github.com/UstadMobile/UstadMobile/assets/78338755/1ff84b86-8cda-4a7c-b5f3-1e794a1c6041)

Expected:

![Screenshot from 2024-03-19 12-44-06](https://github.com/UstadMobile/UstadMobile/assets/78338755/478485e6-5aa9-4d0d-8336-25c9e80bc0a2)

**Comment by mikedawson** [comment]
Resolved with commit https://github.com/UstadMobile/UstadMobile/commit/5d636c17f63734e80273a40c627ff8250238d1f4
