### ISSUE TITLE
Issue noted in Cypress test || web-app || The private comment field is not visible for students to add private comment

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#861]
**Describe the bug**
The private comment field is not visible for students to add private comment

**To Reproduce**
1. Run the cypress test WEB_004_009_group_users_add_private_comments.cy.js

note: Not reproduced manually.

**Expected behavior**
The private comment field is should be visible for students to add private comment

**Screenshots**
![Screenshot from 2024-03-19 12-21-18](https://github.com/UstadMobile/UstadMobile/assets/78338755/9bf937c8-328b-4b1a-9e9c-582a88232f71)

**Comment by mikedawson** [comment]
Resolved with https://github.com/UstadMobile/UstadMobile/commit/5d636c17f63734e80273a40c627ff8250238d1f4
