### ISSUE TITLE
Android app || When the user clicks the remove profile pic button the Add profile pic dialog box not go away -this might confuse the user

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#864]
**Describe the bug**
When the user clicks the remove profile pic button the Add profile pic dialog box not go away -this might confuse the user

**To Reproduce**
1. Go to the person edit page, the user already has a profile pic
2. Click on the profile pic
3. A dialog box appears, click on the remove profile pic button
4. The dialog box remains there asking for the user to add a pic 

**Expected behavior**
When the user clicks remove profile pic button the user should able to save the changes

**Screenshots**
[Screencast from 03-26-2024 02:48:57 PM.webm](https://github.com/UstadMobile/UstadMobile/assets/78338755/5a0cf849-ecac-4176-a44d-9fbfbd7c785d)

**Comment by mikedawson** [comment]
I believe this was fixed with the referenced commit. @poojaustad please check and confirm.

**Comment by poojaustad** [comment]
Fixed.Thanks Mike
