### ISSUE TITLE
Android app || Teacher not able to add already existing content in library to a course as content block

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#865]
**Describe the bug**
Teachers are not able to add already existing content in the library to a course as a content block but able to add new content from file or link

**To Reproduce**
1. Admin added a epub content to library
2. Teacher login and open the course 
3. click on 'EDit'
4. Click on 'Add block'
5. Click on Content
6. Click on My Content tab- The epub content should be visible here but it seems blank

**Expected behavior**
Teachers should be able to add already existing content in the library to a course as a content block

**Screenshots**
![Screenshot from 2024-03-27 16-37-59](https://github.com/UstadMobile/UstadMobile/assets/78338755/0cb9ffd9-3c21-4ad5-8fd4-0be27f3ddbe4)

**Comment by poojaustad** [comment]
![Screenshot from 2024-04-02 18-52-12](https://github.com/UstadMobile/UstadMobile/assets/78338755/ccbbd093-4d3b-4022-9297-6210945f0fb6)

Content not visible in library

**Comment by mikedawson** [comment]
This should be fixed by commit: https://github.com/UstadMobile/UstadMobile/commit/f9e96c3db96a1301241412602bb0ada8b4531e14

**Comment by poojaustad** [comment]
Fixed, Thanks Mike
