### ISSUE TITLE
Individual learner mode and new organization creation

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#888]
1. As an _individual user_ (e.g. parent/caregiver, young person, etc) I want an _individual learner mode_ so that I can use the app to download learning materials for offline usage and track my learning progress without being associated with a school.
2. As an _individual user_ I want _to be able to start using the app with or without creating an account_ so that I can start 100% offline without creating an account or create an account so that I can access it across multiple devices.
3. As a _school principal / admin_ I want an option to add my school / organization.

Criteria / notes:
* If creating an account - this should be linked to a cloud folder provider e.g. initially Google Drive
* An individual user is effectively using only the library feature
* After onboarding empty states need to be shown to guide user on next steps
** e.g. when a new individual user starts for the first time, their library is empty. Guide them
** e.g. when a new organization starts for the first time, their class list is empty. Guide them.
* Course should probably be renamed back to 'class'

**Comment by poojaustad** [comment]
**ACCEPTANCE CRITERIA**

**Scenario 1:** **Given** a new individual user without any prior backup **when** starting the app for the first time **then** should be able to create new local account, add content to library, and backup to file

- User opens app
- User clicks on the "Join as individual learner" button
- Check: the user sees a page with 2 options: "Create new local account" and "Restore from file"
- User clicks on "Create new local account"
- Check: user should be in the library section of the app. Bottom bar should not be shown. Library is empty. User sees prompt/guidance to add something
- User clicks add, imports a content item to the library (e.g. ebook, video, etc)
- Check: content can be opened
- User clicks settings, backup, selects file.
- Check: backup is reported as successfully completed


**Scenario 2:** **Given** an individual user has a pre-existing backup **when** starting the app for the first time **then** user should be able to restore from backup

- User opens app
- User clicks on the "Join as individual learner" button
- Check: the user sees a page with 2 options: "Create new local account" and "Restore from file"
- User clicks on "Restore from file"
- User selects backup file
- Check: user should be taken to library - content that was backed up should be visible as it was before (e.g. from Scenario 1)
- Check: content can be opened

**Scenario 3:**: **Given** a new user wants to add their organization **when** starting the app for the first time **then** user will be directed to Ustad Mobile website.

- Users open app
- User clicks "Add new organization"
- Check: opens ustad mobile website

**Comment by divyahariharan2103** [comment]
Adding the flow and the screenshots below




### **2.Type of user screen**




![Image](https://github.com/UstadMobile/UstadMobile/assets/123718481/2859b4a1-5f67-4143-91f6-6a35f67475ac)





 ### **3. Existing Organization screen**


![Image](https://github.com/UstadMobile/UstadMobile/assets/123718481/017dd97f-8038-4a07-ae4c-111e2bd56914)



### **4. Login Screen**



![Image](https://github.com/UstadMobile/UstadMobile/assets/123718481/8226e364-5aa5-4169-9007-662b5223b912)


### **6. Add new Organization screen**



![Image](https://github.com/UstadMobile/UstadMobile/assets/123718481/4b272964-cfdb-4737-b3c4-163b3b1d3ec7)




### **7. Individual Learner screen**



![Image](https://github.com/UstadMobile/UstadMobile/assets/123718481/eac2229c-45fa-4bb2-8f0c-27e682d92df3)

**Comment by mikedawson** [comment]
Personal mode is already implemented - this task  is obsolete
