### ISSUE TITLE
SCORM support

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#89]
**Is your feature request related to a problem? Please describe.**
Some content authoring tools still don't support Experience API (TinCan). There are still a lot of SCORM files around where the source file isn't readily obtainable or the tool does not support Experience API.

**Describe the solution you'd like**
The ability to open a SCORM file and capture the usage logs as Experience API statements. 

**Describe alternatives you've considered**
Requiring users to use TinCan content

**Additional context**
It might be possible to use this wrapper: https://github.com/adlnet/SCORM-to-xAPI-Wrapper

**Comment by soumyob** [comment]
Experience API?

**Comment by mikedawson** [comment]
Almost all tools support xAPI export, which is the intended successor for SCORM. It could be revisited if needed for legacy content.
