### ISSUE TITLE
Tab-Swiping Bug Affects Floating Action Button

### ISSUE THREAD

**Issue by Prashant-Android** [UstadMobile/UstadMobile#890]
**Bug Description**
When swiping between tabs like "Course", "Members", "Attendance" in the app, the floating action button (FAB) does not update its state properly. It remains unchanged despite switching tabs.

**To Reproduce**
1. Open the app.
2. Navigate to a specific course.
3. Swipe between tabs like "Course", "Members", "Attendance".
4. Notice that the floating action button (FAB) does not update its appearance or functionality accordingly.

**Expected behavior**
The floating action button (FAB) should update dynamically as tabs are swiped, reflecting relevant actions or options corresponding to each tab.

https://github.com/UstadMobile/UstadMobile/assets/170605592/0a6055db-7d87-4023-8c66-42e1e296e35b

**Smartphone (please complete the following information):**
- Device: Realme X
- OS: Android
- Android Version: 10

**Comment by mikedawson** [comment]
https://github.com/UstadMobile/UstadMobile/assets/4280622/604158c9-9f48-4716-b895-a6516613df2a

I think this is fixed with commit as referenced above. @poojaustad  please verify

**Comment by poojaustad** [comment]
Tested. This issue has been fixed. closing this issue. Thanks.
