### ISSUE TITLE
Offline installation of the App

### ISSUE THREAD

**Issue by divyahariharan2103** [UstadMobile/UstadMobile#900]
The purpose of the task is as a (learner/teacher) I want to install the USTAD app on the phone even when the user is offline without any internet or waiting on a slow connection. 
Below are the few use cases with which this can be achieved:
1. If the user has the app file on SD card or a flash drive he should be able to install the application.
2. If a person has the USTAD app on his phone he should be able to share it with others through multiple options like Quickshare, Gmail etc and they should be able to install the app.

Also a person can have the app on his phone with space in his flash drive save the file to file manager and then load it on the SD card

Here basically we need to display a screen with a button where the user will be able to share the app by clicking on the button

Todo: Add new installation section to manual:
Add Android subsection
Add sub-subsection - Install from SD Card/Flash Drive and offline sharing (quickshare, other apps). For each add screenshots for key screens.

**Comment by mikedawson** [comment]
Implemented with pull request: https://github.com/UstadMobile/UstadMobile/pull/908
