### ISSUE TITLE
Individual Learner - Icon Discrepancy on Onboarding Page

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#901]
**Describe the bug**
The icons on the onboarding page do not match the UI design specifications

**To Reproduce**

1. Open the app on an Android device.
2. Navigate to the onboarding page.
3. Compare the icons with design document

**Expected behavior**
Icons on the onboarding page should align with the UI design specifications.

**Screenshots**
![Screenshot from 2024-07-04 15-53-11](https://github.com/UstadMobile/UstadMobile/assets/78338755/8c2468bd-d948-4b2d-8c91-93f7f300b938)

![Screenshot from 2024-07-04 15-40-39](https://github.com/UstadMobile/UstadMobile/assets/78338755/bc9d9345-0eb3-4919-8256-4e5889d1312c)

![Screenshot from 2024-07-04 17-04-08](https://github.com/UstadMobile/UstadMobile/assets/78338755/399b02e0-26cc-479b-9f35-6a91298751aa)

![Screenshot from 2024-07-04 17-12-11](https://github.com/UstadMobile/UstadMobile/assets/78338755/0d5b03d8-d347-4beb-9a8a-646277231188)

**Comment by mikedawson** [comment]
The bar at the top - that gets set by Android - I think we don't need to worry about it. 
The icons - @Prashant-Android please use the icons as per the design. You can ask Akshat if you need links.

**Comment by mikedawson** [comment]
Related to issue #888

**Comment by poojaustad** [comment]
This issue has been fixed. Icons are matching the design. Thanks @Prashant-Android
