### ISSUE TITLE
Exploratory testing for offline asset sharing

### ISSUE THREAD

**Issue by divyahariharan2103** [UstadMobile/UstadMobile#921]
As part of the task the following are being tested:

- [x] The network service discovery

- [x] [Google Nearby](https://developers.google.com/nearby)
- [x] Bluetooth Low Energy streaming
- [x] Wifi direct for large file sharing

**Comment by Prashant-Android** [comment]
• Researched and implemented Google Nearby API and Bluetooth Low Energy streaming for enhanced device communication, including optimizing different connection strategies (P2P_CLUSTER and P2P_STAR).

• Developed mDNSd implementation for network discovery in the desktop version and improved local device discovery and connectivity across platforms.

• Implemented bidirectional file transfer in the Android app with features like original file metadata preservation, accurate transfer speed calculation, progress display, and support for various file types and MIME types.

• Created user-friendly UI components like FileTransferDialog and FileReceiveDialog to display file transfer progress, speed, and status, while optimizing for different screen sizes and orientations.

• Integrated Wi-Fi Direct functionality, including peer discovery, connection establishment, and basic file transfer, complementing existing Google Nearby features.

• Resolved critical issues such as JSON parsing errors, UI thread blocking, socket timeouts, and resource leaks, improving the overall stability and performance of the file transfer process.

• Explored and experimented with additional technologies and codebases, including OneRoasterAPI, Mashrabiya code, and Mesh library, to expand the app's capabilities.

• Continuously refined and organized the codebase, removing unnecessary elements and improving overall code quality and maintainability.
