### ISSUE TITLE
Merge Invitation with Passkeys

### ISSUE THREAD

**Issue by divyahariharan2103** [UstadMobile/UstadMobile#945]
Merge the invitation functionality with the passkey and create a PR

**Comment by Nikunjsharma0** [comment]
Teacher or admin sending invitation link then new user opens the invitation and join the class

https://github.com/user-attachments/assets/bab9eed6-5277-427c-aa38-4e9e53055b1d
https://github.com/user-attachments/assets/65f62a54-72aa-4aa5-8d0f-74c37ca38a70

**Comment by mikedawson** [comment]
@Nikunjsharma0  to create a pull request for this branch - link with this task - and then self-check and review. This will be the pull request to be used to merge passkey support into primary.
