### ISSUE TITLE
Wrong margins on account type screen

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#950]
**Describe the bug**
We must use default jetpack compose marigns as per coding style  to ensure consistency,

https://github.com/user-attachments/assets/382bdb29-8bd0-4554-8abb-db239d05396c

**Comment by mikedawson** [comment]
Affects #906

**Comment by Nikunjsharma0** [comment]
Fixed as per video with commit reference  in Jenkins job https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding-release-learningtree2/2/  - @poojaustad  please confirm







https://github.com/user-attachments/assets/2cbc110d-d1a4-41c3-bf29-4a8c9f40a0e3

**Comment by poojaustad** [comment]
This issue is fixed.Thanks
