### ISSUE TITLE
Personal account user brought to wrong screen on returning to app when reopening the app

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#951]
**Describe the bug**
Personal account user is directed to the wrong screen when they return to the app

**To Reproduce**
1. Signup as new personal user with a passkey
2. Close the app
3. Open the app again
4. Notice that the user is brought to the courses screen - not used for personal accounts

**Expected behavior**
User should return to the library screen

**Comment by mikedawson** [comment]
Blocks task #906

**Comment by Nikunjsharma0** [comment]
Fixed as per video with commit reference  in Jenkins job https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding-release-learningtree2/2/  - @poojaustad   please confirm

https://github.com/user-attachments/assets/81802701-9455-4b94-b0ea-4f19afac672e

**Comment by poojaustad** [comment]
This issue is fixed. Tested. Thanks.
