### ISSUE TITLE
Personal and parental account checkboxes not working

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#952]
**Describe the bug**
Personal and parental account checkboxes not working

**To Reproduce**
1. Click to signup for a new personal account
2. Check I'm a parent then uncheck it 
3. Notice that the checkboxes do not operate independently 

**Expected behavior**
Each checkbox should be independent.

Blocks task #906

**Comment by Nikunjsharma0** [comment]
https://github.com/user-attachments/assets/50e18a58-f571-4c4f-b171-143a08ac79a4

**Comment by poojaustad** [comment]
Tested. Working as expected. Issue fixed.
