### ISSUE TITLE
Going back leads to blank screen when reopening app

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#953]
**Describe the bug**
When a user reopens the app (e.g. after signing up or in for the first time), if the user goes back, they get to a blank screen

**To Reproduce**
1. signup or login
2. close the app
3. open the app
4. tap back - see blank screen

**Expected behavior**
Tapping back should exit the app when there is nothing in the back stack remaining

**Additional context**
I think redirectviewmodel is not setting clearstack as required when doing the first navigation

Blocks task #906

**Comment by Nikunjsharma0** [comment]
https://github.com/user-attachments/assets/697d4e45-f302-4f58-99dc-d201d077c40f

**Comment by poojaustad** [comment]
Tested. Issue is fixed.
