### ISSUE TITLE
Importing a Folder

### ISSUE THREAD

**Issue by divyahariharan2103** [UstadMobile/UstadMobile#972]
### **User Story:**
As an Admin on desktop or android, I want to Import a folder so that I can save time instead of doing file by file.

### **Background info:**

- Currently we have an option to Import a file but now we will need to implement this new feature where the admin is able to import a complete folder
- This option should be provided to only on Desktop or Android
- This option will not be available on Web version (due to security restrictions on web browsers).

### **Implementation tasks:**
@mikedawson to add the tasks

**Comment by mikedawson** [comment]
Behavior note: if unsupported content is found in a selected folder or subfolder, it can be ignored.

**Comment by Anugraha-sutara** [comment]
- The folder import feature has been implemented for Desktop and Android platforms.

[Screen_recording_20241106_102615.webm](https://github.com/user-attachments/assets/a2112a8e-4e71-478d-a742-cd7d06ff3c44)

https://github.com/user-attachments/assets/208bf483-0589-4111-88bf-7345878d42e3

**Comment by poojaustad** [comment]
Testing completed.
