### ISSUE TITLE
Error when uploading H5P file (v.0.4.135), both web and desktop app (RCICT server)

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#976]
**Describe the bug**
Error, when uploading H5P files on RCICT server on both web and desktop app (v. 0.4.135).

**Screenshots**
![error_when_uploading_h5p_webbrowser](https://github.com/user-attachments/assets/5e9085fb-bac0-4c04-a3f0-d749124d3352)
![error_when_uploading_h5p_desktop_app](https://github.com/user-attachments/assets/1f1f9dd6-db57-4d52-bf9b-9cce38e678a1)

**Additional context**

**Comment by mikedawson** [comment]
@komil-pro This looks like the H5P file itself is invalid (specifically it appears that the size of something in the h5p zip does not match). Please share a link to the H5P file.

**Comment by komil-pro** [comment]
yes, please find samples here https://fs.rcict.net/index.php/s/BAKC8jpG56Q3mEt

**Comment by mikedawson** [comment]
@komil-pro this is a link to a folder: please specify an exact file where importing it caused an error

**Comment by komil-pro** [comment]
> @komil-pro this is a link to a folder: please specify an exact file where importing it caused an error

Please find one sample file for checking https://fs.rcict.net/index.php/s/fdKCwXDdBbTML7z

**Comment by poojaustad** [comment]
This issue has been reproduced from my end on android as well. 
[Screencast from 11-12-2024 03:03:53 PM.webm](https://github.com/user-attachments/assets/ef144ee4-fafb-4e42-87eb-f1caf18a0ac1)

**Comment by mikedawson** [comment]
![Screenshot from 2024-11-25 10-59-28](https://github.com/user-attachments/assets/dcb144a3-e8b8-4304-a9f4-a1c2ea86af3c)

The H5P file itself is a corrupt zip as per the screenshot. Some tools were able to extract it (although there may have been data loss).
