### ISSUE TITLE
Display warning message to users for using any social network in the app

### ISSUE THREAD

**Issue by divyahariharan2103** [UstadMobile/UstadMobile#979]
### **User Story:**
As an **User** , I want to see a **message before using any social network inside the app**,  so that **I will be warned before proceeding further.** 

### Background info:

- As per latest Google Playstore policy , the user should be notified/Warned before they  use any social network inside the application

### **Implementation tasks:**
@mikedawson to add the tasks

**Comment by Prashant-Android** [comment]
Desktop Version

https://github.com/user-attachments/assets/54d230ae-1a9c-4cf0-9b62-92f133514208

**Comment by Prashant-Android** [comment]
Mobile Version

https://github.com/user-attachments/assets/a4fe4368-cb6d-4d9a-8bca-d3ae9aa4cc60

**Comment by Prashant-Android** [comment]
Web Version 

https://github.com/user-attachments/assets/b07e959e-3ab7-4a84-82f3-4ba05ec4219e
