### ISSUE TITLE
 User Unable to Log In After Creation by Admin & Admin Cross-Platform Login Issue

### ISSUE THREAD

**Issue by Anugraha-sutara** [UstadMobile/UstadMobile#990]
**Steps to Reproduce:**
Branch: `dev-integrate-analytics-url`
There are two issues encountered during testing:

- A newly created user cannot log in to the app after being added by the admin.

- Logging in as admin on one platform (web or mobile) prevents logging in as admin on the other platform.

**To Reproduce**
**Scenario 1: User Login Issue**

Run the following command:

`./gradlew app-ktor-server:run 
`
`./gradlew app-ktor-server:run --args='newlearningspace --url http://192.168.20.10:8087/ --title learningspace --adminpassword 12345'`

- Log in as admin.

- Create a new person/user from the admin panel.

- Attempt to log in with the new person’s credentials on the app.

**Expected behavior**
The newly created user should be able to log in to the app successfully.

![Screenshot from 2024-12-10 15-38-17](https://github.com/user-attachments/assets/e63f7ee6-ce83-4f8f-a4ca-7790b7afd257)

**Scenario 2: Admin Cross-Platform Login Issue**

- Log in as admin on the web interface.
- Attempt to log in as admin on the mobile app without logging out of the web.

**Expected Result:**
The admin should be able to log in to both web and mobile simultaneously or after logging out.

**Actual Result:**
Logging in as admin on one platform prevents logging in on the other.

**Comment by mikedawson** [comment]
@Anugraha-sutara why is this marked as closed?

**Comment by mikedawson** [comment]
Steps to reproduce needs also needs to mention the branch where this behavior was experienced (as the steps do not describe the current primary branch)

**Comment by Anugraha-sutara** [comment]
The issues were fixed by creating a new branch and merging dev-simplified-onboarding-learningspacemgr into it. On the new branch, everything seems to be working, so it looks like the issue was with the old branch.

Scenario 1: The issue with newly created users not being able to log in was resolved.Can login through the new user
